WITH fotos AS (
  
  SELECT
      CAST("PERIODO" AS DATE) AS "PERIODO",
      CAST("PROMOTOR" AS TEXT) AS "PROMOTOR",
      CAST("PDV" AS TEXT) AS "PDV",
      RTRIM(LTRIM(RTRIM(SPLIT_PART(CAST("ATIVIDADE" AS TEXT), '(', 2), ' )'))) AS "ATIVIDADE",
      RTRIM(LTRIM(RTRIM(CAST("SECAO" AS TEXT), ' :'))) AS "SECAO"
  FROM "scj"."fat_scj_ExportacaodeFotos"
  WHERE CAST("ATIVIDADE" AS TEXT) ILIKE '%GRUPO%'

)

/*Resumo de Atividades*/
SELECT
  CAST(RPL."COORDENADOR" AS TEXT) AS "COORDENADOR",
  CAST(RPL."PERIODO" AS DATE) AS "PERIODO",
  CAST(RPL."PROMOTOR" AS TEXT) AS "PROMOTOR",
  CAST(RPL."PDV" AS TEXT) AS "PDV",
  CAST(RPL."CANAL_DO_PDV" AS TEXT) AS "CANAL DO PDV",
  'CROSS' AS "ATIVIDADE",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NA ÁGUA SANITÁRIA' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NA ÁGUA SANITÁRIA",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NO DETERGENTE' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NO DETERGENTE",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NA FRALDA' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NA FRALDA",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NA PERFUMARIA ADULTO ( OFF )' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NA PERFUMARIA ADULTO__OFF__",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NA PERFUMARIA BEBÊ ( LYSOFORM AEROSOL )' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NA PERFUMARIA BEBÊ__LYSOFORM AEROSOL__",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NA PERFUMARIA BEBÊ ( OFF BABY )' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NA PERFUMARIA BEBÊ__OFF BABY__",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NO PET' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NO PET",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NO PAPEL HIGIÊNICO' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NO PAPEL HIGIÊNICO_BANHEIRO",
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' AND COUNT(CASE WHEN CAST(EF."SECAO" AS TEXT) = 'CROSS NO PAPEL HIGIÊNICO' THEN CAST(EF."SECAO" AS TEXT) ELSE NULL END) >= 1 THEN 1 ELSE 0 END AS "CROSS NO PAPEL HIGIÊNICO_PURIFICADORES",
  COALESCE (CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' THEN 
      (CASE WHEN COUNT( (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN (CASE WHEN EF."SECAO" = 'CROSS ZONA QUENTE' THEN EF."SECAO" ELSE NULL END) ELSE NULL END)) >= 8 THEN 8 
            WHEN COUNT( (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN (CASE WHEN EF."SECAO" = 'CROSS ZONA QUENTE' THEN EF."SECAO" ELSE NULL END) ELSE NULL END)) = 0 THEN 0
            ELSE COUNT( (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN (CASE WHEN EF."SECAO" = 'CROSS ZONA QUENTE' THEN EF."SECAO" ELSE NULL END) ELSE NULL END))
      END)
    ELSE NULL
  END,
  
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) = 'CC' THEN 
      (CASE WHEN COUNT(DISTINCT (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN EF."SECAO" ELSE NULL END)) >= 5 THEN 5
            WHEN COUNT(DISTINCT (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN EF."SECAO" ELSE NULL END)) = 0 THEN NULL
            ELSE COUNT(DISTINCT (CASE WHEN EF."ATIVIDADE" = 'CROSS' THEN EF."SECAO" ELSE NULL END))
      END)
    ELSE NULL
  END) AS "CROSS ZONA QUENTE",

  CAST(NULL AS DOUBLE PRECISION) AS "PONTO EXTRA 1",
  CAST(NULL AS DOUBLE PRECISION) AS "PONTO EXTRA 2",


  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_GLADE",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_INSETICIDAS",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_MR_MUSCULO__LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_PATO",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_GLADE",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_INSETICIDAS",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_MR_MUSCULO__LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_PATO",
  CAST(NULL AS DOUBLE PRECISION) AS "BANDEJA_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "BANDEJA_PURIFICADOR",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_BANHEIROS_SOLIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_BANHEIROS_LIQUIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_INSETICIDA",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_MR MUSCULO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_PURIFICADOR",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_BANHEIROS_SOLIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_BANHEIROS_LIQUIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_INSETICIDA",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_MM COZINHA",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_MM SAPONÁCEO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_PURIFICADOR"

FROM "scj"."fat_scj_RelacaodePromotoreLojas" RPL
LEFT JOIN fotos EF ON (CAST(RPL."PERIODO" AS DATE) = CAST(EF."PERIODO" AS DATE) AND CAST(RPL."PROMOTOR" AS TEXT) = CAST(EF."PROMOTOR" AS TEXT) AND CAST(RPL."PDV" AS TEXT) = CAST(EF."PDV" AS TEXT))
WHERE
    CAST(EF."ATIVIDADE" AS TEXT) = 'CROSS'
GROUP BY 1,2,3,4,5



UNION ALL

SELECT
  CAST(RPL."COORDENADOR" AS TEXT) AS "COORDENADOR",
  CAST(RPL."PERIODO" AS DATE) AS "PERIODO",
  CAST(RPL."PROMOTOR" AS TEXT) AS "PROMOTOR",
  CAST(RPL."PDV" AS TEXT) AS "PDV",
  CAST(RPL."CANAL_DO_PDV" AS TEXT) AS "CANAL DO PDV",
  'PONTO EXTRA' AS "ATIVIDADE",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA ÁGUA SANITÁRIA",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO DETERGENTE",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA FRALDA",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA ADULTO__OFF__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA BEBÊ__LYSOFORM AEROSOL__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA BEBÊ__OFF BABY__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PET",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PAPEL HIGIÊNICO_BANHEIRO",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PAPEL HIGIÊNICO_PURIFICADORES",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS ZONA QUENTE",

  COALESCE(CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END) >= 5 THEN 5
            WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END) = 0 THEN NULL
            ELSE COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END)
      END)
    ELSE NULL
  END,
  
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) = 'CC' THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END) >= 2 THEN 2
            WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END) = 0 THEN NULL 
            ELSE COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('DISPLAY / DISPENSER', 'TEK-SKINA', 'CHECK-STAND') THEN EF."SECAO" ELSE NULL END)
      END)
    ELSE NULL
  END) AS "PONTO EXTRA 1",

  COALESCE(CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) <> 'CC' THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END) >= 3 THEN 3 
            WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END) = 0 THEN NULL
            ELSE COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END)
      END)
    ELSE NULL
  END,
  
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) = 'CC' THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END) >= 3 THEN 3 
            WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END) = 0 THEN NULL 
            ELSE COUNT(CASE WHEN EF."ATIVIDADE" = 'PONTO EXTRA' AND EF."SECAO" IN ('ILHA', 'TERMINAL / PONTA DE GONDOLA', 'PAREDÃO / BLOCAGEM') THEN EF."SECAO" ELSE NULL END)
      END)
    ELSE NULL
  END) AS "PONTO EXTRA 2",

  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_GLADE",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_INSETICIDAS",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_MR_MUSCULO__LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA_PATO",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_GLADE",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_INSETICIDAS",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_MR_MUSCULO__LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "RÉGUA__BANDEJA_PATO",
  CAST(NULL AS DOUBLE PRECISION) AS "BANDEJA_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "BANDEJA_PURIFICADOR",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_BANHEIROS (SOLIDO)",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_BANHEIROS (LIQUIDO)",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_INSETICIDA",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_MR MUSCULO",
  CAST(NULL AS DOUBLE PRECISION) AS "PLANOGRAMA_PURIFICADOR",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_AUTOMOTIVO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_BANHEIROS_SOLIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_BANHEIROS_LIQUIDO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_INSETICIDA",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_LYSOFORM",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_MM COZINHA",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_MM SAPONÁCEO",
  CAST(NULL AS DOUBLE PRECISION) AS "ESPACO_PURIFICADOR"

FROM "scj"."fat_scj_RelacaodePromotoreLojas" RPL
LEFT JOIN fotos EF ON (CAST(RPL."PERIODO" AS DATE) = CAST(EF."PERIODO" AS DATE) AND CAST(RPL."PROMOTOR" AS TEXT) = CAST(EF."PROMOTOR" AS TEXT) AND CAST(RPL."PDV" AS TEXT) = CAST(EF."PDV" AS TEXT))
WHERE
    CAST(EF."ATIVIDADE" AS TEXT) = 'PONTO EXTRA'
GROUP BY 1,2,3,4,5

UNION ALL

SELECT
  CAST(RPL."COORDENADOR" AS TEXT) AS "COORDENADOR",
  CAST(RPL."PERIODO" AS DATE) AS "PERIODO",
  CAST(RPL."PROMOTOR" AS TEXT) AS "PROMOTOR",
  CAST(RPL."PDV" AS TEXT) AS "PDV",
  CAST(RPL."CANAL_DO_PDV" AS TEXT) AS "CANAL DO PDV",
  'GONDOLA' AS "ATIVIDADE",

  /*10*/
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA ÁGUA SANITÁRIA",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO DETERGENTE",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA FRALDA",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA ADULTO__OFF__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA BEBÊ__LYSOFORM AEROSOL__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NA PERFUMARIA BEBÊ__OFF BABY__",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PET",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PAPEL HIGIÊNICO_BANHEIRO",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS NO PAPEL HIGIÊNICO_PURIFICADORES",
  CAST(NULL AS DOUBLE PRECISION) AS "CROSS ZONA QUENTE",

  /*2*/
  CAST(NULL AS DOUBLE PRECISION) AS "PONTO EXTRA 1",
  CAST(NULL AS DOUBLE PRECISION) AS "PONTO EXTRA 2",
  
  /*24*/
  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'PURIFICADORES' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA_GLADE",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'INSETICIDAS' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA_INSETICIDAS",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'MR MUSCULO ( COZINHA / CREMOSO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA_MR_MUSCULO__LYSOFORM",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA_PATO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'PURIFICADORES' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA__BANDEJA_GLADE",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'INSETICIDAS' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA__BANDEJA_INSETICIDAS",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'MR MUSCULO ( COZINHA / CREMOSO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA__BANDEJA_MR_MUSCULO__LYSOFORM",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "RÉGUA__BANDEJA_PATO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'AUTOMOTIVO' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "BANDEJA_AUTOMOTIVO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'PURIFICADORES' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "BANDEJA_PURIFICADOR",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'AUTOMOTIVO' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_AUTOMOTIVO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_BANHEIROS_SOLIDO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_BANHEIROS_LIQUIDO_",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'INSETICIDAS' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_INSETICIDA",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'MR MUSCULO ( COZINHA / CREMOSO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_MR MUSCULO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('KA') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'PURIFICADORES' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "PLANOGRAMA_PURIFICADOR",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'AUTOMOTIVO' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_AUTOMOTIVO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_BANHEIROS_SOLIDO_",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'BANHEIRO ( LIQUIDO / SOLIDO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_BANHEIROS_LIQUIDO_",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'INSETICIDAS' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_INSETICIDA",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'LYSOFORM' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_LYSOFORM",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'MR MUSCULO ( COZINHA / CREMOSO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_MM COZINHA",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'MR MUSCULO ( COZINHA / CREMOSO )' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_MM SAPONÁCEO",

  CASE WHEN CAST(RPL."CANAL_DO_PDV" AS TEXT) IN ('CR', 'CC') THEN 
      (CASE WHEN COUNT(CASE WHEN EF."ATIVIDADE" = 'GONDOLA' AND EF."SECAO" = 'PURIFICADORES' THEN EF."SECAO" ELSE NULL END) >= 1 THEN 1 ELSE 0 END) 
      ELSE 0 
  END AS "ESPACO_PURIFICADOR"
FROM "scj"."fat_scj_RelacaodePromotoreLojas" RPL
LEFT JOIN fotos EF ON (CAST(RPL."PERIODO" AS DATE) = CAST(EF."PERIODO" AS DATE) AND CAST(RPL."PROMOTOR" AS TEXT) = CAST(EF."PROMOTOR" AS TEXT) AND CAST(RPL."PDV" AS TEXT) = CAST(EF."PDV" AS TEXT))
WHERE
    CAST(EF."ATIVIDADE" AS TEXT) = 'GONDOLA'
GROUP BY 1,2,3,4,5