SELECT 
	SUM(VALOR_VENDA_LIQUIDA) AS "VALOR_VENDA_LIQUIDA"
    , SUM(VALOR_MARGEM_GERENCIAL) AS "VALOR_MARGEM_GERENCIAL"
    , SUM(VALOR_TOTAL_PRODUTO) AS "VALOR_TOTAL_PRODUTO" 
FROM VW_FATURAMENTO_BIMACHINE
WHERE DATA_FATURA BETWEEN '2020-09-01' AND '2020-09-30'
AND NOME_CLIENTE NOT IN ('BEL LIMP PRODUTOS DE LIMPEZA LTDA ME','GUIMARAES PROD QUIM E DE LIMPEZA LTDA')
AND GRUPO_PRODUTO IN ('PRODUTO ACABADO')