SELECT DATE_TRUNC('DAY', dd)::DATE AS "Periodo"
FROM GENERATE_SERIES
        (NOW()::TIMESTAMP
        , (DATE_TRUNC('YEAR', NOW()::DATE) - '2 YEAR'::INTERVAL)::TIMESTAMP
        , '- 180 DAYS'::INTERVAL) dd