-- Source: Pedidos - Base
SELECT 
	CAST("Qtde Produtos Completo" AS TEXT) AS "QtdeProdutosCompleto",
	CAST("Tipo de Carteira" AS TEXT) AS "TipodeCarteira",
	CAST("Tipo Faturamento" AS TEXT) AS "TipoFaturamento",
	CAST("Periodo Programado" AS DATE) AS "PeriodoProgramado",
	CAST("Periodo Entrega" AS DATE) AS "PeriodoEntrega",
	CAST("Periodo Programado Filtro" AS DATE) AS "PeriodoProgramadoFiltro",
	CAST("Pedido" AS TEXT) AS "Pedido",
	CAST("Divisao" AS TEXT) AS "Divisao",
	CAST("Grupo Fabricação" AS TEXT) AS "GrupoFabricacao",
	CAST("Especificador" AS TEXT) AS "Especificador",
	CAST("Validade Final Tabela" AS DATE) AS "ValidadeFinalTabela",
	CAST("Produto" AS TEXT) AS "Produto",
	CAST("NF" AS TEXT) AS "NF",
	CAST("Segmento" AS TEXT) AS "Segmento",
	CAST("Tabela de Preços" AS TEXT) AS "TabeladePrecos",
	CAST("Representante Carteira" AS TEXT) AS "RepresentanteCarteira",
	CAST("Validade Final Tabela Filtro" AS DATE) AS "ValidadeFinalTabelaFiltro",
	CAST("Periodo Cad Cliente" AS DATE) AS "PeriodoCadCliente",
	CAST("Motivo" AS TEXT) AS "Motivo",
	CAST("Tipo Pedido Completo" AS TEXT) AS "TipoPedidoCompleto",
	CAST("Cor" AS TEXT) AS "Cor",
	CAST("Cliente" AS TEXT) AS "Cliente",
	CAST("Sub Grupo Produto" AS TEXT) AS "SubGrupoProduto",
	CAST("Justificativa" AS TEXT) AS "Justificativa",
	CAST("Qtde Mix Produtos YOI" AS TEXT) AS "QtdeMixProdutosYOI",
	CAST("Periodo" AS DATE) AS "Periodo",
	CAST("Situacao" AS TEXT) AS "Situacao",
	CAST("Catalogo Produto" AS TEXT) AS "CatalogoProduto",
	CAST("codProduto" AS TEXT) AS "codProduto",
	CAST("Responsavel" AS TEXT) AS "Responsavel",
	CAST("Tipo Pedido" AS TEXT) AS "TipoPedido",
	CAST("Data de Expedicao" AS DATE) AS "DatadeExpedicao",
	CAST("Linha Produto" AS TEXT) AS "LinhaProduto",
	CAST("Validade Inicial Tabela" AS DATE) AS "ValidadeInicialTabela",
	CAST("Periodo Faturado Filtro" AS DATE) AS "PeriodoFaturadoFiltro",
	CAST("Periodo Cadastro" AS DATE) AS "PeriodoCadastro",
	CAST("Agrupamento Cliente" AS TEXT) AS "AgrupamentoCliente",
	CAST("Qtde Clientes" AS TEXT) AS "QtdeClientes",
	CAST("Validade Inicial Tabela Filtro" AS DATE) AS "ValidadeInicialTabelaFiltro",
	CAST("Empresa" AS TEXT) AS "Empresa",
	CAST("Transportador" AS TEXT) AS "Transportador",
	CAST("Tipo Evento" AS TEXT) AS "TipoEvento",
	CAST("Produto Completo" AS TEXT) AS "ProdutoCompleto",
	CAST("UF" AS TEXT) AS "UF",
	CAST("Ordem de Compra" AS TEXT) AS "OrdemdeCompra",
	CAST("Periodo Filtro" AS DATE) AS "PeriodoFiltro",
	CAST("Controle" AS TEXT) AS "Controle",
	CAST("Status Desvio Prazo Prog" AS TEXT) AS "StatusDesvioPrazoProg",
	CAST("Periodo Cadastro Filtro" AS DATE) AS "PeriodoCadastroFiltro",
	CAST("Mercado" AS TEXT) AS "Mercado",
	CAST("Periodo Faturado" AS DATE) AS "PeriodoFaturado",
	CAST("Unidade de Negócio" AS TEXT) AS "UnidadedeNegocio",
	CAST("Feiras" AS TEXT) AS "Feiras",
	CAST("Unidade de Negócio Filtro" AS TEXT) AS "UnidadedeNegocioFiltro",
	CAST("Periodo Liberacao" AS DATE) AS "PeriodoLiberacao",
	CAST("Regiao" AS TEXT) AS "Regiao",
	CAST("Qtde Pedidos" AS TEXT) AS "QtdePedidos",
	CAST("Periodo Movimento" AS DATE) AS "PeriodoMovimento",
	CAST("Controle Desc" AS TEXT) AS "ControleDesc",
	CAST("Representante" AS TEXT) AS "Representante",
	CAST("Qtde Dias 41-45" AS DOUBLE PRECISION) AS "QtdeDias4145",
	CAST("Qde Maxima Cx Master" AS DOUBLE PRECISION) AS "QdeMaximaCxMaster",
	CAST("Vlr Total Pedido" AS DOUBLE PRECISION) AS "VlrTotalPedido",
	CAST("Qtde Dias Cad e Lib" AS DOUBLE PRECISION) AS "QtdeDiasCadeLib",
	CAST("Qtde Caixas Fechadas" AS DOUBLE PRECISION) AS "QtdeCaixasFechadas",
	CAST("Peso Bruto" AS DOUBLE PRECISION) AS "PesoBruto",
	CAST("Preço Tabela" AS DOUBLE PRECISION) AS "PrecoTabela",
	CAST("Qtde Pecas Pedido" AS DOUBLE PRECISION) AS "QtdePecasPedido",
	CAST("Qtde Dias Atraso/Antec" AS DOUBLE PRECISION) AS "QtdeDiasAtrasoAntec",
	CAST("Qtde Pedidos Cx Fechado" AS DOUBLE PRECISION) AS "QtdePedidosCxFechado",
	CAST("Qtde Caixas Total" AS DOUBLE PRECISION) AS "QtdeCaixasTotal",
	CAST("Qtde Dias Prog Comerc" AS DOUBLE PRECISION) AS "QtdeDiasProgComerc",
	CAST("Peso Líquido" AS DOUBLE PRECISION) AS "PesoLiquido",
	CAST("Vlr Mercadoria" AS DOUBLE PRECISION) AS "VlrMercadoria",
	CAST("Dias Analise Comercial" AS DOUBLE PRECISION) AS "DiasAnaliseComercial",
	CAST("Qtde Dias Programação" AS DOUBLE PRECISION) AS "QtdeDiasProgramacao",
	CAST("Qtde Dias Entrega" AS DOUBLE PRECISION) AS "QtdeDiasEntrega",
	CAST("Qtde de Desvio Prazo Prog" AS DOUBLE PRECISION) AS "QtdedeDesvioPrazoProg",
	CAST("Quantidade" AS DOUBLE PRECISION) AS "Quantidade",
	CAST("Volume" AS DOUBLE PRECISION) AS "Volume" 
FROM "ou"."fat_ou_PedidosBase"