-- SANTA MARIA

SELECT
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME) AS PERIODO_EMISSAO,
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME) AS PERIODO_EMISSAO_FILTRO,
  '010'          AS COD_EMPRESA,
  'SANTA MARIA' AS UNIDADE_EMPRESA, 
  SD2.D2_TES AS TIPO_ENTRADA_SAIDA,
  SF4.F4_DESCRI  AS DESCRICAO_TES,
  -- SD2.D2_CF      AS CFOP,
  -- SA1.A1_COD     AS COD_CLIENTE,
  -- SA1.A1_COD     AS QTD_CLIENTE,
  -- SA1.A1_LOJA    AS COD_LOJA,
  -- SA1.A1_NOME    AS CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA        AS QTD_CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA + ' - ' + SA1.A1_NOME  AS CLIENTE,
  SA1.A1_END+','+SA1.A1_BAIRRO+','+SA1.A1_MUN+'-'+SA1.A1_EST+','+(SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS GEO_CLIENTE,  

  SA1.A1_MUN     AS CIDADE,
  SA1.A1_EST     AS UF,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'A2' AND SX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_PRINCIPAL,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = '97' AND SUBSX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_ESPECIFICA,
  (SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS PAIS,
  SA1.A1_SATIV1  AS COD_SEGMENTO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'T3' AND SX5.X5_CHAVE = SA1.A1_SATIV1) AS SEGMENTO,
  SA1.A1_GRPTRIB AS COD_GRUPO_TRIB,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = '21' AND SX5.X5_CHAVE = SA1.A1_GRPTRIB) AS GRUPO_TRIBUTARIO,
  SA1.A1_GRPVEN  AS COD_GRUPO_VEN,
  (SELECT TOP 1 ACY.ACY_DESCRI FROM ACY010 ACY WHERE ACY.ACY_GRPVEN = SA1.A1_GRPVEN) AS GRUPO_VENDA,
  SA3.A3_COD     AS COD_REPRESENTANTE,
  SA3.A3_NREDUZ  AS REPRESENTANTE_REDUZ,
  SA3.A3_NOME    AS REPRESENTANTE,
  SA3.A3_SUPER   AS COD_SUPERVISOR,
  (SELECT TOP 1 SUBSA3.A3_NOME FROM SA3010 SUBSA3 WHERE SUBSA3.A3_COD = SA3.A3_SUPER) AS NOME_SUPERVISOR,

  SB1.B1_COD + ' - ' + SB1.B1_DESC AS DESC_PRODUTO, 
  SB1.B1_COD AS QTD_PRODUTO,
  -- SB1.B1_DESCSIF AS DESC_SIF,
  -- SB1.B1_DESCRED AS PRODUTO_REDUZ,
  SB1.B1_FAM AS COD_FAMILIA,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = 'PS' AND SUBSX5.X5_CHAVE = SB1.B1_FAM) AS DESC_FAMILIA,
  SBM.BM_GRUPO AS COD_GRUPO,
  SBM.BM_DESC AS DESC_GRUPO,
  --ZZ5.ZZ5_TPBONI AS TIPO_BONIFICACAO,
--  COUNT(SF2.F2_DOC)   AS QUANT_NOTAS_VEND,
--  NULL                AS QUANT_NOTAS_DEV,
  --SUM(ZZ5.ZZ5_BONIF) AS VLR_BONIFICACAO,
  SUM(CASE WHEN SD2.D2_TOTAL <> 0 AND SA1.A1_PRAPEL <> 0 THEN SD2.D2_TOTAL - (SD2.D2_TOTAL * (SA1.A1_PRAPEL / 100)) ELSE SD2.D2_TOTAL END) AS VLR_RAPEL,
  SUM(CASE WHEN ZZ5.ZZ5_TPBONI = 'D' THEN ZZ5.ZZ5_BONIF ELSE NULL END) AS VLR_DESCONTO,
  SUM(CASE WHEN ZZ5.ZZ5_TPBONI = 'A' THEN ZZ5.ZZ5_BONIF ELSE NULL END) AS VLR_ACRESCIMO,
  SUM(SD2.D2_QUANT)   AS QTDE_UNITARIA_VEND,
  SUM(SD2.D2_PRUNIT)  AS VLR_UNITARIA_VEND,
  SUM(SD2.D2_TOTAL)   AS VLR_TOTAL_VEND,
  SUM(SD2.D2_PRCVEN)  AS PRECO_PADRAO_VEND,
  SUM(SD2.D2_DESCON)  AS VLR_DESCONTO_ITEM_VEND,
  SUM(SF2.F2_DESCONT) AS VLR_DESCONTO_NOTA_VEND,
  SUM(SD2.D2_VALFRE)  AS VLR_FRETE_VEND,
  SUM(SD2.D2_VALIPI) +
  SUM(SD2.D2_VALICM) +
  SUM(SD2.D2_VALISS) +
  SUM(SD2.D2_VALINS) +
  SUM(SD2.D2_VALPIS) +
  SUM(SD2.D2_VALCOF) +
  SUM(SD2.D2_VALCSL) +
  SUM(SD2.D2_VALIRRF) AS VLR_IMPOSTOS_VEND,  
  NULL AS QTDE_UNITARIA_DEV,
  NULL AS VLR_UNITARIA_DEV,
  NULL AS VLR_TOTAL_DEV,
  NULL AS PRECO_PADRAO_DEV,
  NULL AS VLR_FRETE_DEV,
  NULL AS VLR_IMPOSTOS_DEV
 /*
  Autor.: Cristiano Oliveira | Solicitante: Augusto Fleck | 15/01/2019
  Ação..: Comentada amarracao por cadastro de cliente e amarrado por notas
  Motivo: Houve atualização de vendedores e ocasionou divergências nos dados.
 */
/*
INNER JOIN
    SA3010 SA3 WITH (NOLOCK)
ON  SA3.A3_FILIAL IS NOT NULL
AND SA3.A3_COD    = SA1.A1_VEND
*/
FROM
    SD2010 SD2 WITH (NOLOCK)
INNER JOIN SF2010 SF2 WITH (NOLOCK) ON  SF2.F2_FILIAL = SD2.D2_FILIAL AND SF2.F2_DOC    = SD2.D2_DOC
INNER JOIN SF4010 SF4 WITH (NOLOCK) ON  SF4.F4_FILIAL = SD2.D2_FILIAL AND SF4.F4_CODIGO = SD2.D2_TES
LEFT JOIN ZZ5010 ZZ5 WITH (NOLOCK) ON  ZZ5.ZZ5_NUM = SD2.D2_PREPED AND ZZ5.ZZ5_ITEM = SD2.D2_ITEM
INNER JOIN SA1010 SA1 WITH (NOLOCK) ON  SA1.A1_FILIAL IS NOT NULL AND SA1.A1_COD    = SF2.F2_CLIENTE AND SA1.A1_LOJA   = SF2.F2_LOJA
--INNER JOIN SA3010 SA3 WITH (NOLOCK) ON  SA3.A3_FILIAL IS NOT NULL AND (SA3.A3_COD = SF2.F2_VEND1 OR SA3.A3_COD = SF2.F2_VEND2 OR SA3.A3_COD = SF2.F2_VEND3 OR SA3.A3_COD = SF2.F2_VEND4 OR SA3.A3_COD  = SF2.F2_VEND5)
INNER JOIN SA3010 SA3 WITH (NOLOCK) ON  SA3.A3_FILIAL IS NOT NULL AND (SA3.A3_COD = (CASE 
                                                                                        WHEN SF2.F2_VEND1 <> '' THEN SF2.F2_VEND1 
                                                                                        WHEN SF2.F2_VEND2 <> '' THEN SF2.F2_VEND2 
                                                                                    END))
INNER JOIN SB1010 SB1 WITH (NOLOCK) ON  SB1.B1_FILIAL = SD2.D2_FILIAL AND SB1.B1_COD    = SD2.D2_COD 
INNER JOIN SBM010 SBM WITH (NOLOCK) ON  SBM.BM_FILIAL = SB1.B1_FILIAL AND SBM.BM_GRUPO  = SB1.B1_GRUPO

WHERE
--Q  DATA DE EMISSAO DA SAIDA (EDITAR)
    SD2.D2_EMISSAO >= '20210101'
    AND SD2.D2_EMISSAO <= '20211231'
--AND SD2.D2_EMISSAO <= '20191127'
--  SD2.D2_EMISSAO >= CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(GETDATE())-1),GETDATE()),112) -- Primeiro Dia do Mês Atual
---------------------------------
AND SD2.D2_TIPO NOT IN ('D', 'B')
AND SD2.D2_SERIE = '10'
AND SF4.F4_MSBLQL <> '1'
AND SF4.F4_TIPO = 'S'
AND SF4.F4_DUPLIC = 'S'
AND SF2.F2_TPFRETE IN ('C', 'F', 'S', 'T')
AND SD2.D_E_L_E_T_ <> '*'
AND SF2.D_E_L_E_T_ <> '*'
AND SF4.D_E_L_E_T_ <> '*'
AND SA1.D_E_L_E_T_ <> '*'
AND SA3.D_E_L_E_T_ <> '*'
AND SB1.D_E_L_E_T_ <> '*'
AND SBM.D_E_L_E_T_ <> '*'

GROUP BY
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME),
  SD2.D2_TES,
  SF2.F2_DOC,
  SF2.F2_SERIE,
  SF4.F4_DESCRI,
  SD2.D2_CF,
  SA3.A3_COD,
  SA3.A3_NREDUZ,
  SA3.A3_NOME,
  SA3.A3_SUPER,
  SA1.A1_COD,
  SA1.A1_LOJA,
  SA1.A1_NOME,
  SA1.A1_NREDUZ,
  SA1.A1_END,
  SA1.A1_BAIRRO,
  SA1.A1_MUN,
  SA1.A1_EST,
  SA1.A1_REGIAO,
  SA1.A1_PAIS,
  SA1.A1_GRPTRIB,
  SA1.A1_GRPVEN,
  SA1.A1_SATIV1,
  SB1.B1_COD,
  SB1.B1_COD,
  SB1.B1_DESC,
  SB1.B1_DESCSIF,
  SB1.B1_DESCRED,
  SB1.B1_FAM,
  SBM.BM_GRUPO,
  SBM.BM_DESC--,
  --ZZ5.ZZ5_TPBONI

UNION ALL

-- VALIDACAO DE FATURAMENTO POR TES (ENTRADA = DEVOLUCAO)
SELECT
  CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME) AS PERIODO_EMISSAO,
  CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME) AS PERIODO_EMISSAO_FILTRO,
  '010'          AS COD_EMPRESA,
  'SANTA MARIA' AS UNIDADE_EMPRESA, 
  SD1.D1_TES AS TIPO_ENTRADA_SAIDA,
  SF4.F4_DESCRI  AS DESCRICAO_TES,
  -- SD2.D2_CF      AS CFOP,
  -- SA1.A1_COD     AS COD_CLIENTE,
  -- SA1.A1_COD     AS QTD_CLIENTE,
  -- SA1.A1_LOJA    AS COD_LOJA,
  -- SA1.A1_NOME    AS CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA        AS QTD_CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA + ' - ' + SA1.A1_NOME  AS CLIENTE,
  SA1.A1_END+','+SA1.A1_BAIRRO+','+SA1.A1_MUN+'-'+SA1.A1_EST+','+(SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS GEO_CLIENTE,  

  SA1.A1_MUN     AS CIDADE,
  SA1.A1_EST     AS UF,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'A2' AND SX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_PRINCIPAL,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = '97' AND SUBSX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_ESPECIFICA,
  (SELECT TOP 1 SYA.YA_DESCR FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS PAIS,
  SA1.A1_SATIV1  AS COD_SEGMENTO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'T3' AND SX5.X5_CHAVE = SA1.A1_SATIV1) AS SEGMENTO,
  SA1.A1_GRPTRIB AS COD_GRUPO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = '21' AND SX5.X5_CHAVE = SA1.A1_GRPTRIB) AS GRUPO,
  SA1.A1_GRPVEN  AS COD_GRUPO_VEN,
  (SELECT TOP 1 ACY.ACY_DESCRI FROM ACY010 ACY WHERE ACY.ACY_GRPVEN = SA1.A1_GRPVEN) AS GRUPO_VENDA,
  SA3.A3_COD     AS COD_REPRESENTANTE,
  SA3.A3_NREDUZ  AS NOME_REDUZIDO,
  SA3.A3_NOME    AS REPRESENTANTE,
  SA3.A3_SUPER   AS COD_SUPERVISOR,  
  (SELECT TOP 1 SUBSA3.A3_NOME FROM SA3010 SUBSA3 WHERE SUBSA3.A3_COD = SA3.A3_SUPER) AS NOME_SUPERVISOR,
SB1.B1_COD  + ' - ' + SB1.B1_DESC AS DESC_PRODUTO, 
  SB1.B1_COD AS QTD_PRODUTO,
  -- SB1.B1_DESCSIF AS DESC_SIF,
  -- SB1.B1_DESCRED AS PRODUTO_REDUZ,
  SB1.B1_FAM AS COD_FAMILIA,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = 'PS' AND SUBSX5.X5_CHAVE = SB1.B1_FAM) AS DESC_FAMILIA,
  SBM.BM_GRUPO AS COD_GRUPO,
  SBM.BM_DESC AS DESC_GRUPO,
  --NULL AS TIPO_BONIFICACAO,
--  COUNT(SF2.F2_DOC)   AS QUANT_NOTAS_VEND,
--  NULL                AS QUANT_NOTAS_DEV,
  --NULL AS VLR_BONIFICACAO,
  NULL AS VLR_RAPEL,
  NULL AS VLR_DESCONTO,
  NULL AS VLR_ACRESCIMO,
  NULL  AS QTDE_UNITARIA_VEND,
  NULL AS VLR_UNITARIA_VEND,
  NULL  AS VLR_TOTAL_VEND,
  NULL AS PRECO_PADRAO_VEND,
  NULL  AS VLR_DESCONTO_ITEM_VEND,
  NULL  AS VLR_DESCONTO_NOTA_VEND,
  NULL  AS VLR_FRETE_VEND,
  NULL AS VLR_IMPOSTOS_VEND,
 
  SUM(SD1.D1_QUANT)  AS QTDE_UNITARIA_DEV,
  SUM(SD1.D1_VUNIT)  AS VLR_UNITARIA_DEV,
  SUM(SD1.D1_TOTAL)  AS VLR_TOTAL_DEV,
  SUM(SD1.D1_VUNIT)  AS PRECO_PADRAO_DEV,
  SUM(SD1.D1_VALFRE) AS VLR_FRETE_DEV,
  SUM(SD1.D1_VALIPI) +
  SUM(SD1.D1_VALICM) +
  SUM(SD1.D1_VALISS) +
  SUM(SD1.D1_VALINS) +
  SUM(SD1.D1_VALPIS) +
  SUM(SD1.D1_VALCOF) +
  SUM(SD1.D1_VALCSL) +
  SUM(SD1.D1_VALIRR) AS VLR_IMPOSTOS_DEV

FROM
    SD1010 SD1
    
INNER JOIN SF4010 SF4 ON  SF4.F4_FILIAL = SD1.D1_FILIAL AND SF4.F4_CODIGO = SD1.D1_TES
INNER JOIN SA1010 SA1 WITH (NOLOCK) ON  SA1.A1_FILIAL IS NOT NULL AND SA1.A1_COD    = SD1.D1_FORNECE AND SA1.A1_LOJA   = SD1.D1_LOJA
INNER JOIN SA3010 SA3 WITH (NOLOCK) ON  SA3.A3_FILIAL IS NOT NULL AND SA3.A3_COD    = SA1.A1_VEND
INNER JOIN SB1010 SB1 WITH (NOLOCK) ON  SB1.B1_FILIAL = SD1.D1_FILIAL AND SB1.B1_COD    = SD1.D1_COD
INNER JOIN SBM010 SBM WITH (NOLOCK) ON  SBM.BM_FILIAL = SB1.B1_FILIAL AND SBM.BM_GRUPO  = SB1.B1_GRUPO
WHERE
--  DATA DE DIGITACAO DA ENTRADA (EDITAR)
    SD1.D1_DTDIGIT >= '20210101'
    AND SD1.D1_DTDIGIT <= '20211231'
--AND SD1.D1_DTDIGIT <= '20191127'
--  SD1.D1_DTDIGIT >= CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(GETDATE())-1),GETDATE()),112) -- Primeiro Dia do Mês Atual
--------------------------------
AND SD1.D1_TIPO = 'D'
AND SD1.D1_NFORI <> ''
AND SD1.D1_SERIORI = '10'
AND SF4.F4_TIPO = 'E'
AND SF4.F4_DUPLIC = 'S'
AND SF4.F4_MSBLQL <> '1'
AND SF4.D_E_L_E_T_ <> '*'
AND SD1.D_E_L_E_T_ <> '*'
AND SA1.D_E_L_E_T_ <> '*'
AND SA3.D_E_L_E_T_ <> '*'

GROUP BY
   CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME),
  SD1.D1_TES,
  SD1.D1_DOC,
  SD1.D1_SERIE,
  SF4.F4_DESCRI,
  SD1.D1_CF,
  SA3.A3_COD,
  SA3.A3_NREDUZ,
  SA3.A3_NOME,
  SA3.A3_SUPER,
  SA1.A1_COD,
  SA1.A1_LOJA,
  SA1.A1_NOME,
  SA1.A1_PRICOM,
  SA1.A1_ULTCOM,
  SA1.A1_NREDUZ,  
  SA1.A1_END,
  SA1.A1_BAIRRO,
  SA1.A1_MUN,
  SA1.A1_EST,
  SA1.A1_REGIAO,
  SA1.A1_PAIS,
  SA1.A1_GRPTRIB,
  SA1.A1_GRPVEN,
  SA1.A1_SATIV1,
  SB1.B1_COD,
  SB1.B1_COD,
  SB1.B1_DESC,
  SB1.B1_DESCSIF,
  SB1.B1_DESCRED,
  SB1.B1_FAM,
  SBM.BM_GRUPO,
  SBM.BM_DESC
  
UNION ALL 

-- RIO GRANDE

SELECT
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME) AS PERIODO_EMISSAO,
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME) AS PERIODO_EMISSAO_FILTRO,
  '020'          AS COD_EMPRESA,
  'RIO GRANDE' AS UNIDADE_EMPRESA, 
   SD2.D2_TES AS TIPO_ENTRADA_SAIDA,
  SF4.F4_DESCRI  AS DESCRICAO_TES,
  -- SD2.D2_CF      AS CFOP,
  -- SA1.A1_COD     AS COD_CLIENTE,
  -- SA1.A1_COD     AS QTD_CLIENTE,
  -- SA1.A1_LOJA    AS COD_LOJA,
  -- SA1.A1_NOME    AS CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA        AS QTD_CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA + ' - ' + SA1.A1_NOME  AS CLIENTE,
  SA1.A1_END+','+SA1.A1_BAIRRO+','+SA1.A1_MUN+'-'+SA1.A1_EST+','+(SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS GEO_CLIENTE,  

  SA1.A1_MUN     AS CIDADE,
  SA1.A1_EST     AS UF,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'A2' AND SX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_PRINCIPAL,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = '97' AND SUBSX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_ESPECIFICA,
  (SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS PAIS,
  SA1.A1_SATIV1  AS COD_SEGMENTO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'T3' AND SX5.X5_CHAVE = SA1.A1_SATIV1) AS SEGMENTO,
  SA1.A1_GRPTRIB AS COD_GRUPO_TRIB,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = '21' AND SX5.X5_CHAVE = SA1.A1_GRPTRIB) AS GRUPO_TRIBUTARIO,
  SA1.A1_GRPVEN  AS COD_GRUPO_VEN,
  (SELECT TOP 1 ACY.ACY_DESCRI FROM ACY010 ACY WHERE ACY.ACY_GRPVEN = SA1.A1_GRPVEN) AS GRUPO_VENDA,
  SA3.A3_COD     AS COD_REPRESENTANTE,
  SA3.A3_NREDUZ  AS REPRESENTANTE_REDUZ,
  SA3.A3_NOME    AS REPRESENTANTE,
  SA3.A3_SUPER   AS COD_SUPERVISOR,
  (SELECT TOP 1 SUBSA3.A3_NOME FROM SA3010 SUBSA3 WHERE SUBSA3.A3_COD = SA3.A3_SUPER) AS NOME_SUPERVISOR,

  SB1.B1_COD + ' - ' + SB1.B1_DESC AS DESC_PRODUTO, 
  SB1.B1_COD AS QTD_PRODUTO,
  -- SB1.B1_DESCSIF AS DESC_SIF,
  -- SB1.B1_DESCRED AS PRODUTO_REDUZ,
  SB1.B1_FAM AS COD_FAMILIA,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = 'PS' AND SUBSX5.X5_CHAVE = SB1.B1_FAM) AS DESC_FAMILIA,
  SBM.BM_GRUPO AS COD_GRUPO,
  SBM.BM_DESC AS DESC_GRUPO,
  --ZZ5.ZZ5_TPBONI AS TIPO_BONIFICACAO,

--  COUNT(SF2.F2_DOC)   AS QUANT_NOTAS_VEND,
--  NULL                AS QUANT_NOTAS_DEV,
  --SUM(ZZ5.ZZ5_BONIF) AS VLR_BONIFICACAO, /*currency*/
  SUM(CASE WHEN SD2.D2_TOTAL <> 0 AND SA1.A1_PRAPEL <> 0 THEN SD2.D2_TOTAL - (SD2.D2_TOTAL * (SA1.A1_PRAPEL / 100)) ELSE SD2.D2_TOTAL END) AS VLR_RAPEL,
  SUM(CASE WHEN ZZ5.ZZ5_TPBONI = 'D' THEN ZZ5.ZZ5_BONIF ELSE 0 END) AS VLR_DESCONTO,
  SUM(CASE WHEN ZZ5.ZZ5_TPBONI = 'A' THEN ZZ5.ZZ5_BONIF ELSE 0 END) AS VLR_ACRESCIMO,
  SUM(SD2.D2_QUANT)   AS QTDE_UNITARIA_VEND,
  SUM(SD2.D2_PRUNIT)  AS VLR_UNITARIA_VEND,
  SUM(SD2.D2_TOTAL)   AS VLR_TOTAL_VEND,
  SUM(SD2.D2_PRCVEN)  AS PRECO_PADRAO_VEND,
  SUM(SD2.D2_DESCON)  AS VLR_DESCONTO_ITEM_VEND,
  SUM(SF2.F2_DESCONT) AS VLR_DESCONTO_NOTA_VEND,
  SUM(SD2.D2_VALFRE)  AS VLR_FRETE_VEND,
  SUM(SD2.D2_VALIPI) +
  SUM(SD2.D2_VALICM) +
  SUM(SD2.D2_VALISS) +
  SUM(SD2.D2_VALINS) +
  SUM(SD2.D2_VALPIS) +
  SUM(SD2.D2_VALCOF) +
  SUM(SD2.D2_VALCSL) +
  SUM(SD2.D2_VALIRRF) AS VLR_IMPOSTOS_VEND,  
  NULL AS QTDE_UNITARIA_DEV,
  NULL AS VLR_UNITARIA_DEV,
  NULL AS VLR_TOTAL_DEV,
  NULL AS PRECO_PADRAO_DEV,
  NULL AS VLR_FRETE_DEV,
  NULL AS VLR_IMPOSTOS_DEV

FROM
    SD2010 SD2 WITH (NOLOCK)
INNER JOIN SF2010 SF2 WITH (NOLOCK) ON  SF2.F2_FILIAL = SD2.D2_FILIAL AND SF2.F2_DOC    = SD2.D2_DOC 
INNER JOIN SF4010 SF4 WITH (NOLOCK) ON  SF4.F4_FILIAL = SD2.D2_FILIAL AND SF4.F4_CODIGO = SD2.D2_TES
LEFT JOIN ZZ5010 ZZ5 WITH (NOLOCK) ON  ZZ5.ZZ5_NUM = SD2.D2_PREPED AND ZZ5.ZZ5_ITEM = SD2.D2_ITEM
INNER JOIN SA1010 SA1 WITH (NOLOCK) ON  SA1.A1_FILIAL IS NOT NULL AND SA1.A1_COD    = SF2.F2_CLIENTE AND SA1.A1_LOJA   = SF2.F2_LOJA
INNER JOIN SA3010 SA3 WITH (NOLOCK) ON  SA3.A3_FILIAL IS NOT NULL AND SA3.A3_COD    = SA1.A1_VEND 
INNER JOIN SB1010 SB1 WITH (NOLOCK) ON  SB1.B1_FILIAL = SD2.D2_FILIAL AND SB1.B1_COD    = SD2.D2_COD
INNER JOIN SBM010 SBM WITH (NOLOCK) ON  SBM.BM_FILIAL = SB1.B1_FILIAL AND SBM.BM_GRUPO  = SB1.B1_GRUPO
WHERE
--  DATA DE EMISSAO DA SAIDA (EDITAR)
    SD2.D2_EMISSAO >= '20210101'
    AND SD2.D2_EMISSAO <= '20211231'
--AND SD2.D2_EMISSAO <= '20191127'
--  SD2.D2_EMISSAO >= CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(GETDATE())-1),GETDATE()),112) -- Primeiro Dia do Mês Atual
---------------------------------
AND SD2.D2_TIPO NOT IN ('D', 'B')
AND SD2.D2_SERIE = '20'
AND SF4.F4_MSBLQL <> '1'
AND SF4.F4_TIPO = 'S'
AND SF4.F4_DUPLIC = 'S'
AND SF2.F2_TPFRETE IN ('C', 'F', 'S', 'T')
AND SD2.D_E_L_E_T_ <> '*'
AND SF2.D_E_L_E_T_ <> '*'
AND SF4.D_E_L_E_T_ <> '*'
AND SA1.D_E_L_E_T_ <> '*'
AND SA3.D_E_L_E_T_ <> '*'
AND SB1.D_E_L_E_T_ <> '*'
AND SBM.D_E_L_E_T_ <> '*'

GROUP BY
  CAST(CONVERT(VARCHAR(25),SF2.F2_EMISSAO,112)AS DATETIME),
  SD2.D2_TES,
  SF2.F2_DOC,
  SF2.F2_SERIE,
  SF4.F4_DESCRI,
  SD2.D2_CF,
  SA3.A3_COD,
  SA3.A3_NREDUZ,
  SA3.A3_NOME,
  SA3.A3_SUPER,
  SA1.A1_COD,
  SA1.A1_LOJA,
  SA1.A1_NOME,
  SA1.A1_NREDUZ,
  SA1.A1_END,
  SA1.A1_BAIRRO,
  SA1.A1_MUN,
  SA1.A1_EST,
  SA1.A1_REGIAO,
  SA1.A1_PAIS,
  SA1.A1_GRPTRIB,
  SA1.A1_GRPVEN,
  SA1.A1_SATIV1,
  SB1.B1_COD,
  SB1.B1_COD,
  SB1.B1_DESC,
  SB1.B1_DESCSIF,
  SB1.B1_DESCRED,
  SB1.B1_FAM,
  SBM.BM_GRUPO,
  SBM.BM_DESC--,
  --ZZ5.ZZ5_TPBONI

UNION ALL

-- VALIDACAO DE FATURAMENTO POR TES (ENTRADA = DEVOLUCAO)
SELECT
  CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME) AS PERIODO_EMISSAO,
  CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME) AS PERIODO_EMISSAO_FILTRO,
  '020'          AS COD_EMPRESA,
  'RIO GRANDE' AS UNIDADE_EMPRESA, 
  SD1.D1_TES AS TIPO_ENTRADA_SAIDA,
  SF4.F4_DESCRI  AS DESCRICAO_TES,
  -- SD2.D2_CF      AS CFOP,
  -- SA1.A1_COD     AS COD_CLIENTE,
  -- SA1.A1_COD     AS QTD_CLIENTE,
  -- SA1.A1_LOJA    AS COD_LOJA,
  -- SA1.A1_NOME    AS CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA        AS QTD_CLIENTE,
  SA1.A1_COD + ' - ' + SA1.A1_LOJA + ' - ' + SA1.A1_NOME  AS CLIENTE,
  SA1.A1_END+','+SA1.A1_BAIRRO+','+SA1.A1_MUN+'-'+SA1.A1_EST+','+(SELECT TOP 1 SYA.YA_DESCR  FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS GEO_CLIENTE,  

  SA1.A1_MUN     AS CIDADE,
  SA1.A1_EST     AS UF,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'A2' AND SX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_PRINCIPAL,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = '97' AND SUBSX5.X5_CHAVE = SA1.A1_REGIAO) AS REGIAO_ESPECIFICA,
  (SELECT TOP 1 SYA.YA_DESCR FROM SYA010 SYA WHERE SYA.YA_CODGI = SA1.A1_PAIS) AS PAIS,
  SA1.A1_SATIV1  AS COD_SEGMENTO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = 'T3' AND SX5.X5_CHAVE = SA1.A1_SATIV1) AS SEGMENTO,
  SA1.A1_GRPTRIB AS COD_GRUPO,
  (SELECT TOP 1 SX5.X5_DESCRI FROM SX5010 SX5 WHERE SX5.X5_TABELA = '21' AND SX5.X5_CHAVE = SA1.A1_GRPTRIB) AS GRUPO,
  SA1.A1_GRPVEN  AS COD_GRUPO_VEN,
  (SELECT TOP 1 ACY.ACY_DESCRI FROM ACY010 ACY WHERE ACY.ACY_GRPVEN = SA1.A1_GRPVEN) AS GRUPO_VENDA,
  SA3.A3_COD     AS COD_REPRESENTANTE,
  SA3.A3_NREDUZ  AS NOME_REDUZIDO,
  SA3.A3_NOME    AS REPRESENTANTE,
  SA3.A3_SUPER   AS COD_SUPERVISOR,  
  (SELECT TOP 1 SUBSA3.A3_NOME FROM SA3010 SUBSA3 WHERE SUBSA3.A3_COD = SA3.A3_SUPER) AS NOME_SUPERVISOR,

  SB1.B1_COD + ' - ' + SB1.B1_DESC AS DESC_PRODUTO, 
  SB1.B1_COD AS QTD_PRODUTO,
  -- SB1.B1_DESCSIF AS DESC_SIF,
  -- SB1.B1_DESCRED AS PRODUTO_REDUZ,
  SB1.B1_FAM AS COD_FAMILIA,
  (SELECT TOP 1 X5_DESCRI FROM SX5010 SUBSX5 WHERE SUBSX5.X5_TABELA = 'PS' AND SUBSX5.X5_CHAVE = SB1.B1_FAM) AS DESC_FAMILIA,
  SBM.BM_GRUPO AS COD_GRUPO,
  SBM.BM_DESC AS DESC_GRUPO,
  --NULL AS TIPO_BONIFICACAO,
--  COUNT(SF2.F2_DOC)   AS QUANT_NOTAS_VEND,
--  NULL                AS QUANT_NOTAS_DEV,
  NULL AS VLR_RAPEL,
  NULL AS VLR_DESCONTO,
  NULL AS VLR_ACRESCIMO,
  NULL  AS QTDE_UNITARIA_VEND,
  NULL AS VLR_UNITARIA_VEND,
  NULL  AS VLR_TOTAL_VEND,
  NULL AS PRECO_PADRAO_VEND,
  NULL  AS VLR_DESCONTO_ITEM_VEND,
  NULL  AS VLR_DESCONTO_NOTA_VEND,
  NULL  AS VLR_FRETE_VEND,
  NULL AS VLR_IMPOSTOS_VEND,
 
  SUM(SD1.D1_QUANT)  AS QTDE_UNITARIA_DEV,
  SUM(SD1.D1_VUNIT)  AS VLR_UNITARIA_DEV,
  SUM(SD1.D1_TOTAL)  AS VLR_TOTAL_DEV,
  SUM(SD1.D1_VUNIT)  AS PRECO_PADRAO_DEV,
  SUM(SD1.D1_VALFRE) AS VLR_FRETE_DEV,
  SUM(SD1.D1_VALIPI) +
  SUM(SD1.D1_VALICM) +
  SUM(SD1.D1_VALISS) +
  SUM(SD1.D1_VALINS) +
  SUM(SD1.D1_VALPIS) +
  SUM(SD1.D1_VALCOF) +
  SUM(SD1.D1_VALCSL) +
  SUM(SD1.D1_VALIRR) AS VLR_IMPOSTOS_DEV

FROM
    SD1010 SD1
INNER JOIN SF4010 SF4 ON  SF4.F4_FILIAL = SD1.D1_FILIAL AND SF4.F4_CODIGO = SD1.D1_TES
INNER JOIN SA1010 SA1 WITH (NOLOCK) ON  SA1.A1_FILIAL IS NOT NULL AND SA1.A1_COD    = SD1.D1_FORNECE AND SA1.A1_LOJA   = SD1.D1_LOJA
INNER JOIN SA3010 SA3 WITH (NOLOCK) ON  SA3.A3_FILIAL IS NOT NULL AND SA3.A3_COD    = SA1.A1_VEND
INNER JOIN SB1010 SB1 WITH (NOLOCK) ON  SB1.B1_FILIAL = SD1.D1_FILIAL AND SB1.B1_COD    = SD1.D1_COD
INNER JOIN SBM010 SBM WITH (NOLOCK) ON  SBM.BM_FILIAL = SB1.B1_FILIAL AND SBM.BM_GRUPO  = SB1.B1_GRUPO
WHERE
--  DATA DE DIGITACAO DA ENTRADA (EDITAR)
    SD1.D1_DTDIGIT >= '20210101'
   AND SD1.D1_DTDIGIT <= '20211231'
--AND SD1.D1_DTDIGIT <= '20191127'
--  SD1.D1_DTDIGIT >= CONVERT(VARCHAR(25),DATEADD(dd,-(DAY(GETDATE())-1),GETDATE()),112) -- Primeiro Dia do Mês Atual
--------------------------------
AND SD1.D1_TIPO = 'D'
AND SD1.D1_NFORI <> ''
AND SD1.D1_SERIORI = '20'
AND SF4.F4_TIPO = 'E'
AND SF4.F4_DUPLIC = 'S'
AND SF4.F4_MSBLQL <> '1'
AND SF4.D_E_L_E_T_ <> '*'
AND SD1.D_E_L_E_T_ <> '*'
AND SA1.D_E_L_E_T_ <> '*'
AND SA3.D_E_L_E_T_ <> '*'

GROUP BY
   CAST(CONVERT(VARCHAR(25),SD1.D1_DTDIGIT,112)AS DATETIME),
  SD1.D1_TES,
  SD1.D1_DOC,
  SD1.D1_SERIE,
  SF4.F4_DESCRI,
  SD1.D1_CF,
  SA3.A3_COD,
  SA3.A3_NREDUZ,
  SA3.A3_NOME,
  SA3.A3_SUPER,
  SA1.A1_COD,
  SA1.A1_LOJA,
  SA1.A1_NOME,
  SA1.A1_PRICOM,
  SA1.A1_ULTCOM,
  SA1.A1_NREDUZ,  
  SA1.A1_END,
  SA1.A1_BAIRRO,
  SA1.A1_MUN,
  SA1.A1_EST,
  SA1.A1_REGIAO,
  SA1.A1_PAIS,
  SA1.A1_GRPTRIB,
  SA1.A1_GRPVEN,
  SA1.A1_SATIV1,
  SB1.B1_COD,
  SB1.B1_COD,
  SB1.B1_DESC,
  SB1.B1_DESCSIF,
  SB1.B1_DESCRED,
  SB1.B1_FAM,
  SBM.BM_GRUPO,
  SBM.BM_DESC