SELECT
        --VENDGERE AS COD_GERENTE,
        --VENDEMPE AS COD_EMPRESA_REPRESENTANTE,
        --MASTCODI AS COD_MASTER,
        --MASTDESC AS MASTER,
        --FORN.CADACODI AS CODFORNECEDOR,
        
        CFATDATA AS DATA,
        CFATEORI AS COD_EMPRESA,
        EMP.CADANOME AS EMPRESA,
        CFATREPR AS COD_VENDEDOR,
        REP.CADANOME AS VENDEDOR,
        
        VENDGERE AS COD_GERENTE,
        NULL AS GERENTE,

        CFATCLIE AS COD_CLIENTE,
        CLI.CADANOME AS CLIENTE,
        CASE WHEN CFATCLIE = 5000 THEN 'CONSUMIDOR FINAL' ELSE 'CLIENTE' END AS TIPO_CLIENTE,
        COALESCE(PAISNOME, 'BRASIL') AS PAIS,
        CLI.CADAESTA AS ESTADO,
        CLI.CADACIDA AS CIDADE,
        NULL AS CEP,
        REG.TABEDESC AS REGIAO,
        REPLACE(COALESCE(PAISNOME,'BRASIL')|| ',' || CLI.CADAESTA || ',' || CLI.CADACIDA || ',' || CLI.CADABAIR || ',' || CLI.CADAENDE, '\"', '') AS GEO,
        CINADATA AS DATA_ULTIMA_COMPRA,
        (SELECT CFATDATA FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) AS DATA_PRIMEIRA_COMPRA,
        CASE WHEN (SELECT DATE_TRUNC('MONTH', CFATDATA) FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) = DATE_TRUNC('MONTH', CFATDATA) THEN CFATCLIE END AS QTD_CLIENTES_NOVOS,

        TIPO.TABEDESC AS TIPO_PRODUTO, --PRODUTO NÍVEL 1
        SBTP.TABEDESC AS SUBTIPO_PRODUTO, --PRODUTO NÍVEL 2
        CFAMDESC AS FAMILIA_PRODUTO, --PRODUTO NÍVEL 3
        LINH.TABEDESC AS LINHA_PRODUTO, --PRODUTO NÍVEL 4
        MARCDESC AS MARCA_PRODUTO, --PRODUTO NÍVEL 5

        FORN.CADANOME AS FORNECEDOR,

        IFATCODI AS COD_PRODUTO,
       	CASE WHEN IFATTPRO = 'M' THEN CFIFDESC ELSE PRODDESC END AS PRODUTO,
        CAST(CFATDOCU AS VARCHAR)|| '-' || CAST(CFATSERI AS VARCHAR) AS NOTA_FISCAL,
        CFATOPER AS COD_NATUREZA,
        OPERDESC AS NATUREZA,
        CASE WHEN CFATTIPO = 'VD' THEN 'VENDA' ELSE 'DEVOLUÇÃO' END AS TIPO_FATURAMENTO,

        --CFAMDESC AS FAMILIA_PRODUTO,

        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR)|| '-' || CAST(CFATSERI AS VARCHAR) AS QTDE_NOTAS,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATPEDI AS VARCHAR) AS QTDE_PEDIDOS,

        CFATPEDI AS PEDIDO,

        --FORN.CADANOME AS FORNECEDOR,
        --LINH.TABEDESC AS LINHA,
        --CFATREPR AS CODREPRESENTANTE,
        --CFATDFOR AS FORMAPAGAMENTO,
        --COALESCE((SELECT SUM(FAGRVALO * FAGRDIAS) / SUM(FAGRVALO) FROM ARQFAGR WHERE FAGRORIG = 'CFAT' AND FAGREMPE = CFATEORI AND FAGRDOCU = CFATDOCU AND FAGRSERI = CFATSERI AND FAGRVALO > 0 ),0) AS PRAZOMEDIO,
        --CFATDOCU AS NOTAFISCAL,
        --CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) AS NOTAFISCALUNICA,
        
        --CFATDATA AS DATAMOVIMENTO,
        --REPLACE(REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || EMP.CADAESTA || ',' || EMP.CADACIDA || ',' || EMP.CADABAIR || ',' || EMP.CADAENDE, '\"', ''), '\"', '') AS GEOLOJA,
        
        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODPESB * IFATQUAN) 
            ELSE (PRODPESB * IFATQUAN)*-1
        END AS QTDEITENSVENDIDOSKG,*/
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODLITR * IFATQUAN) 
            ELSE (PRODLITR * IFATQUAN)*-1
        END AS LITRAGEM/*QTDEITENSVENDIDOSLT*/,
        
        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN
            ELSE (IFATQUAN)*-1 
        END  AS QTDETOTALITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPTAB 
            ELSE (IFATPTAB)*-1
        END AS PRECOITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN * IFATPTAB 
            ELSE (IFATQUAN * IFATPTAB)*-1
        END AS VLRMERCADORIA,*/
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATVARI + IFATICMC 
            ELSE  (IFATVARI + IFATICMC)*-1
        END AS VLR_IMPOSTOS,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFATPTAB - IFATPREC) * IFATQUAN + IFATRDES 
            ELSE ((IFATPTAB - IFATPREC)*IFATQUAN+IFATRDES)*-1
        END AS VLR_DESCONTO,
        
        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPLIQ - IFATVARI - IFATICMC
            ELSE (IFATPLIQ - IFATVARI - IFATICMC)*-1
        END AS VLRNFITEM,*/
        
        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATRFRE+IFATRSEG+IFATRODE 
            ELSE (IFATRFRE + IFATRSEG + IFATRODE)*-1
        END AS VALORESACESSORIOS,*/
        
  		CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPLIQ     
            ELSE (IFATPLIQ) * -1  
        END AS FATURAMENTO/*VALORPRODUTOS*/,
        
    	CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATFIXO
            ELSE (IFATFIXO)*-1
        END AS VALOR_CUSTO_FIXO,
        
        /*TPVN.TABEDESC AS REPRESENTANTENI,
        TPCL.TABEDESC AS CLIENTENI,
        SUBT.TABEDESC AS CLIENTENII,*/
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN
            COALESCE((SELECT SUM(SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, COALESCE(IFIFPROD, IFATCODI), 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S'))
                        FROM ARQIFAT AS A
                        LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
                        WHERE ITEM.IFATCPRI = A.IFATCPRI), 0)
            ELSE COALESCE((SELECT SUM(SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, COALESCE(IFIFPROD, IFATCODI), 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S'))
                            FROM ARQIFAT AS A
                            LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
                            WHERE ITEM.IFATCPRI = A.IFATCPRI), 0) 
        END AS CMV

        
FROM ARQIFAT ITEM
LEFT JOIN ARQCFAT NOTA ON CFATCPRI = IFATCFAT
LEFT JOIN ARQOPER ON OPERCODI = CFATOPER
LEFT JOIN ARQCADA EMP ON EMP.CADACODI = CFATEORI
LEFT JOIN ARQCADA REP ON REP.CADACODI = CFATREPR
LEFT JOIN ARQCADA CLI ON CLI.CADACODI = CFATCLIE
LEFT JOIN ARQCLIE ON CLIECODI = CFATCLIE
LEFT JOIN ARQVEND ON VENDCODI = CFATREPR
LEFT JOIN ARQTABE TPVN ON TPVN.TABEINDI = 30 AND TPVN.TABECODI = VENDTPVN
LEFT JOIN ARQTABE TPCL ON TPCL.TABEINDI = 10 AND TPCL.TABECODI = CLIETPCL
LEFT JOIN ARQTABE SUBT ON SUBT.TABEINDI = 11 AND SUBT.TABECODI = CLIESUBT
LEFT JOIN ARQPAIS ON CLI.CADACPAI = PAISCPRI
LEFT JOIN ARQTABE REG ON REG.TABEINDI = 15 AND REG.TABECODI = CLI.CADAREGI
LEFT JOIN ARQCFIF ON CFIFEMPE = IFATEMPE AND CFIFDOCU = IFATDOCU AND CFIFSERI = IFATSERI AND CFIFSEQU = IFATSEQU AND CFIFORIG = 'IFAT'
LEFT JOIN ARQPROD ON PRODCODI = CASE WHEN IFATTPRO = 'P' THEN IFATCODI ELSE CFIFBASE END
LEFT JOIN ARQMAST ON MASTCODI = PRODMAST
LEFT JOIN ARQTABE TIPO ON TIPO.TABEINDI = 100 AND TIPO.TABECODI = MASTTIPO
LEFT JOIN ARQTABE SBTP ON SBTP.TABEINDI = 110 AND SBTP.TABECODI = MASTSUBT
LEFT JOIN ARQTABE LINH ON LINH.TABEINDI = 120 AND LINH.TABECODI = MASTGRUP
LEFT JOIN ARQMARC ON MARCCODI = MASTMARC
LEFT JOIN ARQCINA ON CINACLIE= CFATCLIE
LEFT JOIN ARQCFAM ON CFAMCODI = MASTFAMI
LEFT JOIN ARQCADA FORN ON FORN.CADACODI = MASTFORN
WHERE OPERDESC IN ('DEV. VENDA ENT. FUT.', 'DEV.VENDA MERC.AD.RECEB.TERC.', 'DEV. SIMPLES FATURAMENTO', 'VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') AND 
CFATTIPO NOT IN ( 'VL' ) AND 
CFATDATA >= (NOW()::DATE-30) AND CFATDATA < NOW()::DATE AND 
CFATSTAT <> 'C' AND 
IFATTPRO <> 'M' AND 
CFATEORI NOT IN (098,099,101,899,900,901,902,903)

UNION ALL

SELECT
        CFATDATA AS DATA,
        CFATEORI AS COD_EMPRESA,
        EMP.CADANOME AS EMPRESA,
        CFATREPR AS COD_VENDEDOR,
        REP.CADANOME AS VENDEDOR,
        
        VENDGERE AS CODGERENTE,
        NULL AS GERENTE,

        CFATCLIE AS COD_CLIENTE,
        CLI.CADANOME AS CLIENTE,
        CASE WHEN CFATCLIE = 5000 THEN 'CONSUMIDOR FINAL' ELSE 'CLIENTE' END AS TIPO_CLIENTE,  
        COALESCE(PAISNOME, 'BRASIL') AS PAIS,
        CLI.CADAESTA AS ESTADO,
        CLI.CADACIDA AS CIDADE,
        NULL AS CEP,
        REG.TABEDESC AS REGIAO,
        REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || CLI.CADAESTA || ',' || CLI.CADACIDA || ',' || CLI.CADABAIR || ',' || CLI.CADAENDE, '\"', '') AS GEO,
        CINADATA AS DATA_ULTIMA_COMPRA,
        (SELECT CFATDATA FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) AS DATA_PRIMEIRA_COMPRA,
        CASE WHEN (SELECT DATE_TRUNC('MONTH', CFATDATA) FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) = DATE_TRUNC('MONTH', CFATDATA) THEN CFATCLIE END AS QTD_CLIENTES_NOVOS,
        
        TIPO.TABEDESC AS TIPO_PRODUTO, --PRIMEIRO NÍVEL DO PRODUTO
        SBTP.TABEDESC AS SUBTIPO_PRODUTO, --SEGUNDO NÍVEL DO PRODUTO
        CFAMDESC AS FAMILIA_PRODUTO, --TERCEIRO NÍVEL DO PRODUTO
        LINH.TABEDESC AS LINHA_PRODUTO, --QUARTO NÍVEL DO PRODUTO
        MARCDESC AS MARCA_PRODUTO, --QUINTO NÍVEL DO PRODUTO
        FORN.CADANOME AS FORNECEDOR,
        IFIFPROD AS COD_PRODUTO,
        PRODDESC AS PRODUTO,
        
        CAST(CFATDOCU AS VARCHAR) || '-' || CAST(CFATSERI AS VARCHAR) AS NOTA_FISCAL,
        CFATOPER AS COD_NATUREZA,
        OPERDESC AS NATUREZA,
        CASE WHEN CFATTIPO = 'VD' THEN 'VENDA' ELSE 'DEVOLUÇÃO' END AS TIPO_FATURAMENTO,

        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) || '-' || CAST(CFATSERI AS VARCHAR) AS QTDE_NOTAS,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATPEDI AS VARCHAR) AS QTDE_PEDIDOS,
    	
        CFATPEDI AS PEDIDO,
        /*
        VENDEMPE AS CODEMPRESAREPRESENTANTE,
        MASTCODI AS CODMASTER,
        MASTDESC AS DESCRICAOMASTER,
        FORN.CADACODI AS CODFORNECEDOR,
        FORN.CADANOME AS NOMEFORNECEDOR,
        LINH.TABEDESC AS LINHA,
        CFATREPR AS CODREPRESENTANTE,
        CFATDFOR AS FORMAPAGAMENTO,
        COALESCE((SELECT SUM(FAGRVALO * FAGRDIAS) / SUM(FAGRVALO) FROM ARQFAGR WHERE FAGRORIG = 'CFAT' AND FAGREMPE = CFATEORI AND FAGRDOCU = CFATDOCU AND FAGRSERI = CFATSERI AND FAGRVALO > 0 ),0) AS PRAZOMEDIO,
        CFATDOCU AS NOTAFISCAL,
        
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) AS NOTAFISCALUNICA,
        
        CFATOPER AS CODNATUREZAOPERACAO,
        OPERDESC AS DESCRICAONATUREZAOPERACAO,
        CFATDATA AS DATAMOVIMENTO,
	    REPLACE(REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || EMP.CADAESTA || ',' || EMP.CADACIDA || ',' || EMP.CADABAIR || ',' || EMP.CADAENDE, '\"', ''), '\"', '') AS GEOLOJA,
        
        
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODPESB * IFATQUAN* IFIFQBAX) 
            ELSE (PRODPESB * IFATQUAN* IFIFQBAX)*-1 
        END AS QTDEITENSVENDIDOSKG,*/
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODLITR * IFATQUAN* IFIFQBAX) 
            ELSE (PRODLITR * IFATQUAN* IFIFQBAX)*-1 
        END AS LITRAGEM/*QTDEITENSVENDIDOSLT*/,

        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN*IFIFQBAX 
            ELSE (IFATQUAN*IFIFQBAX)*-1 
        END AS QTDETOTALITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFPTAB 
            ELSE IFIFPTAB*-1
        END AS PRECOITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN * IFIFQBAX * IFIFPTAB
           ELSE IFATQUAN * IFIFQBAX * IFIFPTAB  *-1 
        END AS VLRMERCADORIA,*/
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFVARI + IFIFICMC
            ELSE (IFIFVARI + IFIFICMC)*-1 
        END AS VLR_IMPOSTOS,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFIFPTAB *IFIFQBAX *IFATQUAN) - IFIFPLIQ 
            ELSE ((IFIFPTAB *IFIFQBAX *IFATQUAN ) - IFIFPLIQ)*-1 
        END AS VLR_DESCONTO,

        /*CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFIFPLIQ - (IFIFVARI + IFIFICMC)) 
            ELSE ((IFIFPLIQ - (IFIFVARI + IFIFICMC )))*-1 
        END AS VLRNFITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFRFRE+IFIFRSEG+IFIFRODE  
            ELSE (IFIFRFRE+IFIFRSEG+IFIFRODE) *-1
        END AS VALORESACESSORIOS,*/
  
  		CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFPLIQ
  		    ELSE (IFIFPLIQ)*-1 
        END AS FATURAMENTO,
  
    	CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFFIXO 
            ELSE (IFIFFIXO)*-1 
        END AS VALOR_CUSTO_FIXO,

        /*
        TPVN.TABEDESC AS REPRESENTANTENI,
        TPCL.TABEDESC AS CLIENTENI,
        SUBT.TABEDESC AS CLIENTENII,
        
        CFAMDESC AS FAMILIA,
        */
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN 
            SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, IFIFPROD, 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S')
            ELSE (SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, IFIFPROD, 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S')) 
        END AS CMV

        
FROM ARQCFAT NOTA
LEFT JOIN ARQIFAT ITEM ON CFATCPRI = IFATCFAT
LEFT JOIN ARQOPER ON OPERCODI = CFATOPER
LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
LEFT JOIN ARQCADA EMP ON EMP.CADACODI = CFATEORI
LEFT JOIN ARQCADA REP ON REP.CADACODI = CFATREPR
LEFT JOIN ARQCADA CLI ON CLI.CADACODI = CFATCLIE
LEFT JOIN ARQCLIE ON CLIECODI = CFATCLIE
LEFT JOIN ARQVEND ON VENDCODI = CFATREPR
LEFT JOIN ARQTABE TPVN ON TPVN.TABEINDI = 30 AND TPVN.TABECODI = VENDTPVN
LEFT JOIN ARQTABE TPCL ON TPCL.TABEINDI = 10 AND TPCL.TABECODI = CLIETPCL
LEFT JOIN ARQTABE SUBT ON SUBT.TABEINDI = 11 AND SUBT.TABECODI = CLIESUBT
LEFT JOIN ARQPAIS ON CLI.CADACPAI = PAISCPRI
LEFT JOIN ARQTABE REG ON REG.TABEINDI = 15 AND REG.TABECODI = CLI.CADAREGI
LEFT JOIN ARQCFIF ON CFIFEMPE = IFATEMPE AND CFIFDOCU = IFATDOCU AND CFIFSERI = IFATSERI AND CFIFSEQU = IFATSEQU AND CFIFORIG = 'IFAT'
LEFT JOIN ARQPROD ON PRODCODI = IFIFPROD
LEFT JOIN ARQMAST ON MASTCODI = PRODMAST
LEFT JOIN ARQTABE TIPO ON TIPO.TABEINDI = 100 AND TIPO.TABECODI = MASTTIPO
LEFT JOIN ARQTABE SBTP ON SBTP.TABEINDI = 110 AND SBTP.TABECODI = MASTSUBT
LEFT JOIN ARQTABE LINH ON LINH.TABEINDI = 120 AND LINH.TABECODI = MASTGRUP
LEFT JOIN ARQMARC ON MARCCODI = MASTMARC
LEFT JOIN ARQCINA ON CINACLIE= CFATCLIE
LEFT JOIN ARQCFAM ON CFAMCODI = MASTFAMI
LEFT JOIN ARQCADA FORN ON FORN.CADACODI = MASTFORN
WHERE OPERDESC IN ('DEV. VENDA ENT. FUT.', 'DEV.VENDA MERC.AD.RECEB.TERC.', 'DEV. SIMPLES FATURAMENTO', 'VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') AND 
CFATTIPO NOT IN ( 'VL' ) AND 
CFATDATA >= (NOW()::DATE-30) AND CFATDATA < NOW()::DATE AND 
CFATSTAT <> 'C' AND
IFATTPRO = 'M' AND 
CFATEORI NOT IN (098,099,101,899,900,901,902,903)