SELECT
        VENDGERE AS CODGERENTE,
        VENDEMPE AS CODEMPRESAREPRESENTANTE,
        MASTCODI AS CODMASTER,
        MASTDESC AS DESCRICAOMASTER,
        FORN.CADACODI AS CODFORNECEDOR,
        FORN.CADANOME AS NOMEFORNECEDOR,
        LINH.TABEDESC AS LINHA,
        CFATREPR AS CODREPRESENTANTE,
        CFATDFOR AS FORMAPAGAMENTO,
        COALESCE((SELECT SUM(FAGRVALO * FAGRDIAS) / SUM(FAGRVALO) FROM ARQFAGR WHERE FAGRORIG = 'CFAT' AND FAGREMPE = CFATEORI AND FAGRDOCU = CFATDOCU AND FAGRSERI = CFATSERI AND FAGRVALO > 0 ),0) AS PRAZOMEDIO,
        REPLACE(COALESCE(PAISNOME,'BRASIL')|| ',' || CLI.CADAESTA || ',' || CLI.CADACIDA || ',' || CLI.CADABAIR || ',' || CLI.CADAENDE, '\"', '') AS GEOCLIENTE ,
        CFATDOCU AS NOTAFISCAL,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR)|| '-' || CAST(CFATSERI AS VARCHAR) AS NOTAFISCALCONT,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) AS NOTAFISCALUNICA,
        CFATPEDI AS PEDIDO,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATPEDI AS VARCHAR) AS PEDIDOCONT,
        CASE WHEN CFATTIPO = 'VD' THEN 'VENDA' ELSE 'DEVOLUÇÃO' END AS TIPONOTAFISCAL,
        CFATOPER AS CODNATUREZAOPERACAO,
        OPERDESC AS DESCRICAONATUREZAOPERACAO,
        CFATDATA AS PERIODO,
        CFATDATA AS DATAMOVIMENTO,
        CINADATA AS DATAULTIMACOMPRA,
        (SELECT CFATDATA FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) AS DATAPRIMEIRACOMPRA,
        REG.TABEDESC AS REGIAO,
        CLI.CADAESTA AS ESTADO,
        CLI.CADACIDA AS CIDADE,
        CFATEORI AS CODUNIDADEEMPRESA,
        EMP.CADANOME AS UNIDADEEMPRESA,
        CFATREPR AS CODREPRESENTANTECONT,
        REP.CADANOME AS REPRESENTANTE,
        CFATCLIE AS CODCLIENTECONT,
        CLI.CADANOME AS CLIENTE,
        CASE WHEN CFATCLIE = 5000 THEN 'CONSUMIDOR FINAL' ELSE 'CLIENTE' END AS TIPOCLIENTE,
      	REPLACE(REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || EMP.CADAESTA || ',' || EMP.CADACIDA || ',' || EMP.CADABAIR || ',' || EMP.CADAENDE, '\"', ''), '\"', '') AS GEOLOJA,
        IFATCODI AS CODITEMCONT,
       	CASE WHEN IFATTPRO = 'M' THEN CFIFDESC ELSE PRODDESC END AS ITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODPESB * IFATQUAN) 
            ELSE (PRODPESB * IFATQUAN)*-1
        END AS QTDEITENSVENDIDOSKG,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODLITR * IFATQUAN) 
            ELSE (PRODLITR * IFATQUAN)*-1
        END AS QTDEITENSVENDIDOSLT,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN
            ELSE (IFATQUAN)*-1 
        END  AS QTDETOTALITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPTAB 
            ELSE (IFATPTAB)*-1
        END AS PRECOITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN * IFATPTAB 
            ELSE (IFATQUAN * IFATPTAB)*-1
        END AS VLRMERCADORIA,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATVARI + IFATICMC 
            ELSE  (IFATVARI + IFATICMC)*-1
        END AS VLRIMPOSTOS,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFATPTAB - IFATPREC) * IFATQUAN + IFATRDES 
            ELSE ((IFATPTAB - IFATPREC)*IFATQUAN+IFATRDES)*-1
        END AS VLRDESCONTO,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPLIQ - IFATVARI - IFATICMC
            ELSE (IFATPLIQ - IFATVARI - IFATICMC)*-1
        END AS VLRNFITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATRFRE+IFATRSEG+IFATRODE 
            ELSE (IFATRFRE + IFATRSEG + IFATRODE)*-1
        END AS VALORESACESSORIOS,
        
  		CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATPLIQ     
            ELSE (IFATPLIQ) * -1  
        END AS VALORPRODUTOS,
        
    	CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATFIXO
            ELSE (IFATFIXO)*-1
        END AS VALORCUSTOFIXO,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATVARI
            ELSE (IFATVARI)*-1
        END AS VALORCUSTOVARIAVEL,
        
        TPVN.TABEDESC AS REPRESENTANTENI,
        TPCL.TABEDESC AS CLIENTENI,
        SUBT.TABEDESC AS CLIENTENII,
        TIPO.TABEDESC AS ITEMNI,
        SBTP.TABEDESC AS ITEMNII,
        CFAMDESC AS FAMILIA,
        MARCDESC AS ITEMNIII,
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN
            COALESCE((SELECT SUM(SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, COALESCE(IFIFPROD, IFATCODI), 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S'))
                        FROM ARQIFAT AS A
                        LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
                        WHERE ITEM.IFATCPRI = A.IFATCPRI), 0)
            ELSE COALESCE((SELECT SUM(SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, COALESCE(IFIFPROD, IFATCODI), 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S'))
                            FROM ARQIFAT AS A
                            LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
                            WHERE ITEM.IFATCPRI = A.IFATCPRI), 0) 
        END AS CMV,

        CASE WHEN (SELECT DATE_TRUNC('MONTH', CFATDATA) FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) = DATE_TRUNC('MONTH', CFATDATA) THEN CFATCLIE END AS QTDCLIENTESNOVOS
FROM ARQIFAT ITEM
LEFT JOIN ARQCFAT NOTA ON CFATCPRI = IFATCFAT
LEFT JOIN ARQOPER ON OPERCODI = CFATOPER
LEFT JOIN ARQCADA EMP ON EMP.CADACODI = CFATEORI
LEFT JOIN ARQCADA REP ON REP.CADACODI = CFATREPR
LEFT JOIN ARQCADA CLI ON CLI.CADACODI = CFATCLIE
LEFT JOIN ARQCLIE ON CLIECODI = CFATCLIE
LEFT JOIN ARQVEND ON VENDCODI = CFATREPR
LEFT JOIN ARQTABE TPVN ON TPVN.TABEINDI = 30 AND TPVN.TABECODI = VENDTPVN
LEFT JOIN ARQTABE TPCL ON TPCL.TABEINDI = 10 AND TPCL.TABECODI = CLIETPCL
LEFT JOIN ARQTABE SUBT ON SUBT.TABEINDI = 11 AND SUBT.TABECODI = CLIESUBT
LEFT JOIN ARQPAIS ON CLI.CADACPAI = PAISCPRI
LEFT JOIN ARQTABE REG ON REG.TABEINDI = 15 AND REG.TABECODI = CLI.CADAREGI
LEFT JOIN ARQCFIF ON CFIFEMPE = IFATEMPE AND CFIFDOCU = IFATDOCU AND CFIFSERI = IFATSERI AND CFIFSEQU = IFATSEQU AND CFIFORIG = 'IFAT'
LEFT JOIN ARQPROD ON PRODCODI = CASE WHEN IFATTPRO = 'P' THEN IFATCODI ELSE CFIFBASE END
LEFT JOIN ARQMAST ON MASTCODI = PRODMAST
LEFT JOIN ARQTABE TIPO ON TIPO.TABEINDI = 100 AND TIPO.TABECODI = MASTTIPO
LEFT JOIN ARQTABE SBTP ON SBTP.TABEINDI = 110 AND SBTP.TABECODI = MASTSUBT
LEFT JOIN ARQTABE LINH ON LINH.TABEINDI = 120 AND LINH.TABECODI = MASTGRUP
LEFT JOIN ARQMARC ON MARCCODI = MASTMARC
LEFT JOIN ARQCINA ON CINACLIE= CFATCLIE
LEFT JOIN ARQCFAM ON CFAMCODI = MASTFAMI
LEFT JOIN ARQCADA FORN ON FORN.CADACODI = MASTFORN
WHERE OPERDESC IN ('DEV. VENDA ENT. FUT.', 'DEV.VENDA MERC.AD.RECEB.TERC.', 'DEV. SIMPLES FATURAMENTO', 'VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') AND 
CFATTIPO NOT IN ( 'VL' ) AND 
CFATDATA >= DATE_TRUNC('YEAR', NOW()::DATE) - '1 YEAR'::INTERVAL AND CFATDATA <= NOW()::DATE AND 
CFATSTAT = 'C' AND 
IFATTPRO <> 'M' AND 
CFATEORI NOT IN (099,101,899,900,901,902,903) AND
CFATTIPO IN ('VD', 'DC' )


UNION ALL

SELECT
        VENDGERE AS CODGERENTE,
        VENDEMPE AS CODEMPRESAREPRESENTANTE,
        MASTCODI AS CODMASTER,
        MASTDESC AS DESCRICAOMASTER,
        FORN.CADACODI AS CODFORNECEDOR,
        FORN.CADANOME AS NOMEFORNECEDOR,
        LINH.TABEDESC AS LINHA,
        CFATREPR AS CODREPRESENTANTE,
        CFATDFOR AS FORMAPAGAMENTO,
        COALESCE((SELECT SUM(FAGRVALO * FAGRDIAS) / SUM(FAGRVALO) FROM ARQFAGR WHERE FAGRORIG = 'CFAT' AND FAGREMPE = CFATEORI AND FAGRDOCU = CFATDOCU AND FAGRSERI = CFATSERI AND FAGRVALO > 0 ),0) AS PRAZOMEDIO,
        REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || CLI.CADAESTA || ',' || CLI.CADACIDA || ',' || CLI.CADABAIR || ',' || CLI.CADAENDE, '\"', '') AS GEOCLIENTE ,
        CFATDOCU AS NOTAFISCAL,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) || '-' || CAST(CFATSERI AS VARCHAR) AS NOTAFISCALCONT,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATDOCU AS VARCHAR) AS NOTAFISCALUNICA,
    	CFATPEDI AS PEDIDO,
        CAST(CFATEORI AS VARCHAR) ||'-'|| CAST(CFATCLIE AS VARCHAR) ||'-'|| CAST(CFATPEDI AS VARCHAR) AS PEDIDOCONT,
        CASE WHEN CFATTIPO = 'VD' THEN 'VENDA' ELSE 'DEVOLUÇÃO' END AS TIPONOTAFISCAL,
        CFATOPER AS CODNATUREZAOPERACAO,
        OPERDESC AS DESCRICAONATUREZAOPERACAO,
        CFATDATA AS PERIODO,
        CFATDATA AS DATAMOVIMENTO,
        CINADATA AS DATAULTIMACOMPRA,
        (SELECT CFATDATA FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) AS DATAPRIMEIRACOMPRA,
        REG.TABEDESC AS REGIAO,
        CLI.CADAESTA AS ESTADO,
        CLI.CADACIDA AS CIDADE,
        CFATEORI AS CODUNIDADEEMPRESA,
        EMP.CADANOME AS UNIDADEEMPRESA,
        CFATREPR AS CODREPRESENTANTECONT,
        REP.CADANOME AS REPRESENTANTE,
        CFATCLIE AS CODCLIENTECONT,
        CLI.CADANOME AS CLIENTE,
        CASE WHEN CFATCLIE = 5000 THEN 'CONSUMIDOR FINAL' ELSE 'CLIENTE' END AS TIPOCLIENTE,  
	    REPLACE(REPLACE(COALESCE(PAISNOME, 'BRASIL') || ',' || EMP.CADAESTA || ',' || EMP.CADACIDA || ',' || EMP.CADABAIR || ',' || EMP.CADAENDE, '\"', ''), '\"', '') AS GEOLOJA,
        IFIFPROD AS CODITEMCONT,
        PRODDESC AS ITEM,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODPESB * IFATQUAN* IFIFQBAX) 
            ELSE (PRODPESB * IFATQUAN* IFIFQBAX)*-1 
        END AS QTDEITENSVENDIDOSKG,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (PRODLITR * IFATQUAN* IFIFQBAX) 
            ELSE (PRODLITR * IFATQUAN* IFIFQBAX)*-1 
        END AS QTDEITENSVENDIDOSLT,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN*IFIFQBAX 
            ELSE (IFATQUAN*IFIFQBAX)*-1 
        END AS QTDETOTALITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFPTAB 
            ELSE IFIFPTAB*-1
        END AS PRECOITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFATQUAN * IFIFQBAX * IFIFPTAB
           ELSE IFATQUAN * IFIFQBAX * IFIFPTAB  *-1 
        END AS VLRMERCADORIA,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFVARI + IFIFICMC
            ELSE (IFIFVARI + IFIFICMC)*-1 
        END AS VLRIMPOSTOS,
        
        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFIFPTAB *IFIFQBAX *IFATQUAN) - IFIFPLIQ 
            ELSE ((IFIFPTAB *IFIFQBAX *IFATQUAN ) - IFIFPLIQ)*-1 
        END AS VLRDESCONTO,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN (IFIFPLIQ - (IFIFVARI + IFIFICMC)) 
            ELSE ((IFIFPLIQ - (IFIFVARI + IFIFICMC )))*-1 
        END AS VLRNFITEM,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFRFRE+IFIFRSEG+IFIFRODE  
            ELSE (IFIFRFRE+IFIFRSEG+IFIFRODE) *-1
        END AS VALORESACESSORIOS,
  
  		CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFPLIQ
  		    ELSE (IFIFPLIQ)*-1 
        END AS VALORPRODUTOS,
  
    	CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFFIXO 
            ELSE (IFIFFIXO)*-1 
        END AS VALORCUSTOFIXO,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN IFIFVARI
            ELSE (IFIFVARI)*-1 
        END AS VALORCUSTOVARIAVEL,

        TPVN.TABEDESC AS REPRESENTANTENI,
        TPCL.TABEDESC AS CLIENTENI,
        SUBT.TABEDESC AS CLIENTENII,
        TIPO.TABEDESC AS ITEMNI,
        SBTP.TABEDESC AS ITEMNII,
        CFAMDESC AS FAMILIA,
        MARCDESC AS ITEMNIII,

        CASE WHEN TRIM(OPERDESC) IN ('VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') THEN 
            SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, IFIFPROD, 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S')
            ELSE (SHXGETCUSTOITEMV10(IFATEMPE, IFATDOCU, IFATSERI, IFATSEQU, IFIFPROD, 'CMED', FALSE, (IFATTIPO = 'DC' OR IFATTIPO = 'DL'), CFATFUTU = 'S')) 
        END AS CMV, 

        CASE WHEN (SELECT DATE_TRUNC('MONTH', CFATDATA) FROM ARQCFAT WHERE CFATTIPO = 'VD' AND CFATSTAT <> 'C' AND CFATCLIE = NOTA.CFATCLIE ORDER BY CFATCLIE, CFATDATA LIMIT 1) = DATE_TRUNC('MONTH', CFATDATA) THEN CFATCLIE END AS QTDCLIENTESNOVOS
FROM ARQCFAT NOTA
LEFT JOIN ARQIFAT ITEM ON CFATCPRI = IFATCFAT
LEFT JOIN ARQOPER ON OPERCODI = CFATOPER
LEFT JOIN ARQIFIF ON IFATEMPE = IFIFEMPE AND IFATDOCU = IFIFDOCU AND IFATSERI = IFIFSERI AND IFATSEQU = IFIFSEQU AND IFIFORIG = 'IFAT'
LEFT JOIN ARQCADA EMP ON EMP.CADACODI = CFATEORI
LEFT JOIN ARQCADA REP ON REP.CADACODI = CFATREPR
LEFT JOIN ARQCADA CLI ON CLI.CADACODI = CFATCLIE
LEFT JOIN ARQCLIE ON CLIECODI = CFATCLIE
LEFT JOIN ARQVEND ON VENDCODI = CFATREPR
LEFT JOIN ARQTABE TPVN ON TPVN.TABEINDI = 30 AND TPVN.TABECODI = VENDTPVN
LEFT JOIN ARQTABE TPCL ON TPCL.TABEINDI = 10 AND TPCL.TABECODI = CLIETPCL
LEFT JOIN ARQTABE SUBT ON SUBT.TABEINDI = 11 AND SUBT.TABECODI = CLIESUBT
LEFT JOIN ARQPAIS ON CLI.CADACPAI = PAISCPRI
LEFT JOIN ARQTABE REG ON REG.TABEINDI = 15 AND REG.TABECODI = CLI.CADAREGI
LEFT JOIN ARQCFIF ON CFIFEMPE = IFATEMPE AND CFIFDOCU = IFATDOCU AND CFIFSERI = IFATSERI AND CFIFSEQU = IFATSEQU AND CFIFORIG = 'IFAT'
LEFT JOIN ARQPROD ON PRODCODI = IFIFPROD
LEFT JOIN ARQMAST ON MASTCODI = PRODMAST
LEFT JOIN ARQTABE TIPO ON TIPO.TABEINDI = 100 AND TIPO.TABECODI = MASTTIPO
LEFT JOIN ARQTABE SBTP ON SBTP.TABEINDI = 110 AND SBTP.TABECODI = MASTSUBT
LEFT JOIN ARQTABE LINH ON LINH.TABEINDI = 120 AND LINH.TABECODI = MASTGRUP
LEFT JOIN ARQMARC ON MARCCODI = MASTMARC
LEFT JOIN ARQCINA ON CINACLIE= CFATCLIE
LEFT JOIN ARQCFAM ON CFAMCODI = MASTFAMI
LEFT JOIN ARQCADA FORN ON FORN.CADACODI = MASTFORN
WHERE OPERDESC IN ('DEV. VENDA ENT. FUT.', 'DEV.VENDA MERC.AD.RECEB.TERC.', 'DEV. SIMPLES FATURAMENTO', 'VENDA ADQ.TERC. ENCOM.ENT.FUT.', 'VENDA MERC.REC.TERC.', 'SIMPLES FATURAMENTO') AND 
CFATTIPO NOT IN ( 'VL' ) AND 
CFATDATA >= DATE_TRUNC('YEAR', NOW()::DATE) - '1 YEAR'::INTERVAL AND CFATDATA <= NOW()::DATE AND 
CFATSTAT = 'C' AND
IFATTPRO = 'M' AND 
CFATEORI NOT IN (099,101,899,900,901,902,903) AND
CFATTIPO IN ('VD', 'DC' )