SELECT 

	COUNT(DISTINCT NOTAFISCALCONT) 

FROM (
SELECT
BIIFGERE AS CODGERENTE,
VEND.BI_CADAEMPE AS CODEMPRESAREPRESENTANTE,
PROD.BI_PRODMAST AS CODMASTER,
MAST.BI_MASTDESC AS DESCRICAOMASTER,
PROD.BI_PRODFORN AS CODFORNECEDOR,
FORN.BI_CADANOME AS NOMEFORNECEDOR,
GRIT.BI_TABEDESC AS LINHA,
BIIFREPR AS CODREPRESENTANTE,
BIIFDFOR AS FORMAPAGAMENTO,
BIIFPRAZ AS PRAZOMEDIO,
REPLACE( REPLACE( CONCAT( 'BRASIL',',',CLIE.BI_CADAESTA,',',CLIE.BI_CADACIDA,',',CLIE.BI_CADACEPA ),'\"' , ''),'\'', '') AS GEOCLIENTE,
BIIFDOCU AS NOTAFISCAL,
CAST (BIIFEFAT AS VARCHAR) ||''|| CAST (BIIFCLIE AS VARCHAR) ||''|| CAST (BIIFDOCU AS VARCHAR)||CAST(biifseri AS VARCHAR) AS NOTAFISCALCONT,
CAST (BIIFEFAT AS VARCHAR) ||'-'|| CAST (BIIFDOCU AS VARCHAR) AS NOTAFISCALUNICA,
BIIFPEDI AS PEDIDO,
CAST (BIIFEFAT AS VARCHAR) ||''|| CAST (BIIFCLIE AS VARCHAR) ||''|| CAST (BIIFPEDI AS VARCHAR) AS PEDIDOCONT,
CASE WHEN BIIFVTOT >= 0 THEN 'VENDA' ELSE 'DEVOLUÇÃO' END AS TIPONOTAFISCAL,
BIIFDATA AS PERIODO,
BIIFDATA AS DATAMOVIMENTO,
( SELECT MAX(BIIFDATA) FROM BI_BIIF INTERNO WHERE INTERNO.BIIFCLIE = EXTERNO.BIIFCLIE AND INTERNO.BIIFVTOT >= 0 ) AS DATAULTIMACOMPRA,
( SELECT MIN(BIIFDATA) FROM BI_BIIF INTERNO WHERE INTERNO.BIIFCLIE = EXTERNO.BIIFCLIE AND INTERNO.BIIFVTOT >= 0 ) AS DATAPRIMEIRACOMPRA,
REGI.BI_TABEDESC AS REGIAO,
CLIE.BI_CADAESTA AS ESTADO,
CLIE.BI_CADACIDA AS CIDADE,
BIIFEMPE AS CODUNIDADEEMPRESA,
EMPE.BI_CADANOME AS UNIDADEEMPRESA,
BIIFREPR AS CODREPRESENTANTECONT,
VEND.BI_CADANOME AS REPRESENTANTE,
BIIFCLIE AS CODCLIENTECONT,
CLIE.BI_CADANOME AS CLIENTE,
CASE WHEN BIIFCLIE = 5000 THEN 'CONSUMIDOR FINAL' ELSE 'CLIENTE' END AS "TIPO CLIENTE",
REPLACE( REPLACE( CONCAT( 'BRASIL',',',EMPE.BI_CADAESTA,',',EMPE.BI_CADACIDA,',',EMPE.BI_CADACEPA ),'\"' , ''),'\'', '') AS GEOLOJA,
BIIFCODI AS CODITEMCONT,
PROD.BI_PRODDESC AS ITEM,
BIIFVQUI AS QTDEITENSVENDIDOSKG,
BIIFVLIT AS QTDEITENSVENDIDOSLT,
BIIFQUAN AS QTDETOTALITEM,
BIIFPTAB / CASE WHEN BIIFQUAN <> 0 THEN BIIFQUAN ELSE 1 END AS PRECOITEM,
BIIFPTAB AS VLRMERCADORIA,
BIIFVARI + BIIFICMC AS VLRIMPOSTOS,
BIIFPTAB-BIIFPLIQ AS VLRDESCONTO,
BIIFPLIQ - BIIFVARI - BIIFICMC AS VLRNFITEM,
BIIFRFRE+BIIFRSEG+BIIFRODE AS VALORESACESSORIOS,
BIIFPLIQ AS VALORPRODUTOS ,
BIIFFIXO AS VALORCUSTOFIXO ,
TPVN.BI_TABEDESC AS REPRESENTANTENI,
TPCL.BI_TABEDESC AS CLIENTENI,
SUBT.BI_TABEDESC AS CLIENTENII,
TIPO.BI_TABEDESC AS ITEMNI,
SBTP.BI_TABEDESC AS ITEMNII,
BI_CFAMDESC AS FAMILIA,
BI_MARCDESC AS ITEMNIII,
BIIFCMED AS CMV,
CASE WHEN ( SELECT DATE_TRUNC('MONTH',MIN(INTERNO.BIIFDATA))
FROM BI_BIIF INTERNO
WHERE INTERNO.BIIFCLIE = EXTERNO.BIIFCLIE
AND INTERNO.BIIFVTOT >= 0 ) = DATE_TRUNC('MONTH', BIIFDATA)
AND
( SELECT DATE_TRUNC('YEAR',MIN(INTERNO.BIIFDATA))
FROM BI_BIIF INTERNO
WHERE INTERNO.BIIFCLIE = EXTERNO.BIIFCLIE
AND INTERNO.BIIFVTOT >= 0 ) = DATE_TRUNC('YEAR', BIIFDATA)
THEN BIIFCLIE END AS QTDCLIENTESNOVOS,
biifvtot AS "vlr_total"
FROM BI_BIIF EXTERNO
LEFT JOIN BI_CADA EMPE ON EMPE.BI_CADACODI = BIIFEMPE
LEFT JOIN BI_CADA CLIE ON CLIE.BI_CADACODI = BIIFCLIE
LEFT JOIN BI_TABE REGI ON REGI.BI_TABEINDI = 15 AND REGI.BI_TABECODI = CLIE.BI_CADAREGI
LEFT JOIN BI_TABE TPCL ON TPCL.BI_TABEINDI = 10 AND TPCL.BI_TABECODI = CLIE.BI_CADATPCL
LEFT JOIN BI_TABE SUBT ON SUBT.BI_TABEINDI = 11 AND SUBT.BI_TABECODI = CLIE.BI_CADASUBT
LEFT JOIN BI_CADA VEND ON VEND.BI_CADACODI = BIIFVEND
LEFT JOIN BI_TABE TPVN ON TPVN.BI_TABEINDI = 30 AND TPVN.BI_TABECODI = VEND.BI_CADATPVN
LEFT JOIN BI_PROD PROD ON PROD.BI_PRODCODI = BIIFCODI
LEFT JOIN BI_MAST MAST ON MAST.BI_MASTCODI = PROD.BI_PRODMAST
LEFT JOIN BI_CADA FORN ON FORN.BI_CADACODI = PROD.BI_PRODFORN
LEFT JOIN BI_TABE TIPO ON TIPO.BI_TABEINDI = 100 AND TIPO.BI_TABECODI = PROD.BI_PRODTIPO
LEFT JOIN BI_TABE SBTP ON SBTP.BI_TABEINDI = 110 AND SBTP.BI_TABECODI = PROD.BI_PRODSUBT
LEFT JOIN BI_TABE GRIT ON GRIT.BI_TABEINDI = 120 AND GRIT.BI_TABECODI = PROD.BI_PRODGRUP
LEFT JOIN BI_MARC MARC ON MARC.BI_MARCCODI = PROD.BI_PRODMARC
LEFT JOIN BI_CFAM CFAM ON CFAM.BI_CFAMCODI = PROD.BI_PRODFAMI
WHERE
BIIFEMPE NOT IN (100,101)
AND BIIFDATA BETWEEN '2021-01-01' AND '2021-01-31') X --WHERE TIPONOTAFISCAL = 'VENDA'