-- Source: Pedidos em Aberto
SELECT 
	CAST(null AS TEXT) AS "representante",
	CAST(null AS TEXT) AS "dtpedido",
	CAST("CIDADE" AS TEXT) AS "cidade",
	CAST("DTVENDA" AS TEXT) AS "dtvenda",
	CAST("GRUPOPRODUTO" AS TEXT) AS "grupoproduto",
	CAST(null AS TEXT) AS "cliente",
	CAST(null AS TEXT) AS "empresa",
	CAST(null AS TEXT) AS "pais",
	CAST(null AS TEXT) AS "geo",
	CAST("DTAPREVENTREGA" AS TEXT) AS "DtPrevEntrega",
	CAST(null AS TEXT) AS "idempresa",
	CAST(null AS TEXT) AS "tiporepresentante",
	CAST(null AS TEXT) AS "tipofaturamento",
	CAST("PERIODO" AS DATE) AS "periodo",
	CAST("NUMPEDIDO" AS TEXT) AS "numpedido",
	CAST(null AS TEXT) AS "tipocliente",
	CAST("ITEM" AS TEXT) AS "item",
	CAST("NOMEABRE" AS TEXT) AS "nomeabrev",
	CAST(null AS TEXT) AS "subgrupoproduto",
	CAST(null AS DOUBLE PRECISION) AS "kgmeta",
	CAST(null AS DOUBLE PRECISION) AS "vlrvendaliquida",
	CAST(null AS DOUBLE PRECISION) AS "vlricms",
	CAST(null AS DOUBLE PRECISION) AS "qtdcliente",
	CAST(null AS DOUBLE PRECISION) AS "prazo",
	CAST(null AS DOUBLE PRECISION) AS "vlrdesconto",
	CAST(null AS DOUBLE PRECISION) AS "qtd",
	CAST(null AS DOUBLE PRECISION) AS "qtdkg",
	CAST(null AS DOUBLE PRECISION) AS "vlrimpostos",
	CAST(null AS DOUBLE PRECISION) AS "vlrcusto",
	CAST(null AS DOUBLE PRECISION) AS "qtdproduto",
	CAST(null AS DOUBLE PRECISION) AS "vlr",
	CAST("QTDEPEDIDOS" AS DOUBLE PRECISION) AS "qtdepedidos",
	CAST(null AS DOUBLE PRECISION) AS "vlrmercadoria",
	CAST(null AS DOUBLE PRECISION) AS "vlrrentabilidade",
	CAST(null AS DOUBLE PRECISION) AS "qtdrepresentante",
	CAST(null AS DOUBLE PRECISION) AS "vlrmeta",
	CAST(null AS DOUBLE PRECISION) AS "util",
	CAST(null AS DOUBLE PRECISION) AS "qtdlt",
	CAST(null AS DOUBLE PRECISION) AS "vlrmargem",
	CAST(null AS DOUBLE PRECISION) AS "vlrvariavel",
	CAST(null AS DOUBLE PRECISION) AS "vlrpiscofins",
	CAST(null AS DOUBLE PRECISION) AS "vlrfixo",
	CAST(null AS DOUBLE PRECISION) AS "vlrfrete",
	CAST(null AS DOUBLE PRECISION) AS "vlrtabela",
	CAST(null AS DOUBLE PRECISION) AS "ltmeta",
	CAST("VLRPEDIDOS_BRUTO" AS DOUBLE PRECISION) AS "vlrpedidos" 
FROM "guimaraespl"."fat_guimaraespl_PedidosemAberto"