SELECT
    PERIODO
    , NUMPEDIDO
    , CODITEM
    , ITEM
    , CODREPRESENTANTE
    , QTDEPEDIDOS
    , CODCLIENTE
    , VLRPEDIDOS_BRUTO
    , VLRPEDIDOS_LIQUIDO
    , CIDADE
    , ESTADO
    , GRUPOPRODUTO
    , NOMEABRE
    , CFOP
    , DTVENDA
    , DTAPREVENTREGA
    , STATUS
FROM VW_PEDIDOS_BIMACHINE