SELECT  GRUPO_PRODUTO
        , SUM(QUANTIDADE_VENDIDA)        AS "quantidade_vendida"
        , SUM(QTDE_DEVOLVIDA)			AS "quantidade_devolvida"
        , SUM(QUANTIDADE_VENDIDA) - SUM(QTDE_DEVOLVIDA) AS "quantidade_comercializada"
FROM VW_FATURAMENTO_BIMACHINE
WHERE COD_CLIENTE NOT IN ('21')
AND DATA_FATURA BETWEEN '2020-12-01' AND '2020-12-31'
AND LINHA_PRODUTO = '5L'
GROUP BY GRUPO_PRODUTO