SELECT 
	DATE_TRUNC('MONTH', CAST("data_fatura" AS DATE)) AS "datafatura",
	CAST("numero_documento" AS TEXT) AS "numerodocumento",
	CAST("tipo_cliente" AS TEXT) AS "tipocliente",
	CAST("cod_vendedor" AS TEXT) AS "codvendedor",
	CAST("cod_produto" AS TEXT) AS "codproduto",
	CAST("produto" AS TEXT) AS "produto",
	CAST("pais_cliente" AS TEXT) AS "paiscliente",
	CAST("nome_vendedor" AS TEXT) AS "nomevendedor",
	CAST("marca_produto" AS TEXT) AS "marcaproduto",
	CAST("tipo_vendedor" AS TEXT) AS "tipovendedor",
	CAST("estado_cliente" AS TEXT) AS "estadocliente",
	CAST("linha_produto" AS TEXT) AS "linhaproduto",
	CAST("cod_cliente" AS TEXT) AS "codcliente",
	CAST("tipo_faturamento" AS TEXT) AS "tipofaturamento",
	CAST("nome_supervisor" AS TEXT) AS "nomesupervisor",
	CAST("cod_supervisor" AS TEXT) AS "codsupervisor",
	CAST("geo_cliente" AS TEXT) AS "geocliente",
	CAST("nome_cliente" AS TEXT) AS "nomecliente",
	CAST("subgrupo_produto" AS TEXT) AS "subgrupoproduto",
	CAST("cfop" AS TEXT) AS "cfop",
	CAST("cod_filial" AS TEXT) AS "codfilial",
	CAST("cidade_cliente" AS TEXT) AS "cidadecliente",
	CAST("grupo_produto" AS TEXT) AS "grupoproduto",
	CAST("familia_produto" AS TEXT) AS "familiaproduto",
	CAST("cep_cliente" AS TEXT) AS "cepcliente",
	CAST("numero_nota" AS TEXT) AS "numeronota",
	CAST("data_meta" AS DATE) AS "datameta",
	CAST("nome_filial" AS TEXT) AS "nomefilial",
	SUM(CAST("valor_total_produto" AS DOUBLE PRECISION)) AS "valortotalproduto",
	SUM(CAST("valor_venda_liquida" AS DOUBLE PRECISION)) AS "valorvendaliquida",
	SUM(CAST("valor_desconto_fatura" AS DOUBLE PRECISION)) AS "valordescontofatura",
	SUM(CAST("valor_margem_gerencial" AS DOUBLE PRECISION)) AS "valormargemgerencial",
	SUM(CAST("preco_produto" AS DOUBLE PRECISION)) AS "precoproduto",
	SUM(CAST("valor_acrescimo_fatura" AS DOUBLE PRECISION)) AS "valoracrescimofatura",
	--SUM(CAST("valor_pis_cofins" AS DOUBLE PRECISION)) AS "valorpiscofins",
	--SUM(CAST("valor_impostos_fatura" AS DOUBLE PRECISION)) AS "valorimpostosfatura",
	SUM(CAST("valor_margem" AS DOUBLE PRECISION)) AS "valormargem",
	SUM(CAST("custo_total_produto" AS DOUBLE PRECISION)) AS "custototalproduto",
	SUM(CAST("valor_frete_fatura" AS DOUBLE PRECISION)) AS "valorfretefatura",
	SUM(CAST("litros_vendidos" AS DOUBLE PRECISION)) AS "litrosvendidos",
	--SUM(CAST("valor_icms" AS DOUBLE PRECISION)) AS "valoricms",
	SUM(CAST("kilos_vendidos" AS DOUBLE PRECISION)) AS "kilosvendidos",
	SUM(CAST("quantidade_vendida" AS DOUBLE PRECISION)) AS "quantidadevendida" 
FROM "alimentosv2"."fat_alimentosv2_FaturamentoBase"
WHERE DATE_TRUNC('YEAR', CAST("data_fatura" AS DATE)) = '2019-01-01'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28

UNION ALL 

SELECT 
	DATE_TRUNC('MONTH', CAST("data_fatura" AS DATE)) + '1 YEAR' AS "datafatura",
	CAST("numero_documento" AS TEXT) AS "numerodocumento",
	CAST("tipo_cliente" AS TEXT) AS "tipocliente",
	CAST("cod_vendedor" AS TEXT) AS "codvendedor",
	CAST("cod_produto" AS TEXT) AS "codproduto",
	CAST("produto" AS TEXT) AS "produto",
	CAST("pais_cliente" AS TEXT) AS "paiscliente",
	CAST("nome_vendedor" AS TEXT) AS "nomevendedor",
	CAST("marca_produto" AS TEXT) AS "marcaproduto",
	CAST("tipo_vendedor" AS TEXT) AS "tipovendedor",
	CAST("estado_cliente" AS TEXT) AS "estadocliente",
	CAST("linha_produto" AS TEXT) AS "linhaproduto",
	CAST("cod_cliente" AS TEXT) AS "codcliente",
	CAST("tipo_faturamento" AS TEXT) AS "tipofaturamento",
	CAST("nome_supervisor" AS TEXT) AS "nomesupervisor",
	CAST("cod_supervisor" AS TEXT) AS "codsupervisor",
	CAST("geo_cliente" AS TEXT) AS "geocliente",
	CAST("nome_cliente" AS TEXT) AS "nomecliente",
	CAST("subgrupo_produto" AS TEXT) AS "subgrupoproduto",
	CAST("cfop" AS TEXT) AS "cfop",
	CAST("cod_filial" AS TEXT) AS "codfilial",
	CAST("cidade_cliente" AS TEXT) AS "cidadecliente",
	CAST("grupo_produto" AS TEXT) AS "grupoproduto",
	CAST("familia_produto" AS TEXT) AS "familiaproduto",
	CAST("cep_cliente" AS TEXT) AS "cepcliente",
	CAST("numero_nota" AS TEXT) AS "numeronota",
	CAST("data_meta" AS DATE) AS "datameta",
	CAST("nome_filial" AS TEXT) AS "nomefilial",
	SUM(CAST("valor_total_produto" AS DOUBLE PRECISION)) AS "valortotalproduto",
	SUM(CAST("valor_venda_liquida" AS DOUBLE PRECISION)) AS "valorvendaliquida",
	SUM(CAST("valor_desconto_fatura" AS DOUBLE PRECISION)) AS "valordescontofatura",
	SUM(CAST("valor_margem_gerencial" AS DOUBLE PRECISION)) AS "valormargemgerencial",
	SUM(CAST("preco_produto" AS DOUBLE PRECISION)) AS "precoproduto",
	SUM(CAST("valor_acrescimo_fatura" AS DOUBLE PRECISION)) AS "valoracrescimofatura",
	--SUM(CAST("valor_pis_cofins" AS DOUBLE PRECISION)) AS "valorpiscofins",
	--SUM(CAST("valor_impostos_fatura" AS DOUBLE PRECISION)) AS "valorimpostosfatura",
	SUM(CAST("valor_margem" AS DOUBLE PRECISION)) AS "valormargem",
	SUM(CAST("custo_total_produto" AS DOUBLE PRECISION)) AS "custototalproduto",
	SUM(CAST("valor_frete_fatura" AS DOUBLE PRECISION)) AS "valorfretefatura",
	SUM(CAST("litros_vendidos" AS DOUBLE PRECISION)) AS "litrosvendidos",
	--SUM(CAST("valor_icms" AS DOUBLE PRECISION)) AS "valoricms",
	SUM(CAST("kilos_vendidos" AS DOUBLE PRECISION)) AS "kilosvendidos",
	SUM(CAST("quantidade_vendida" AS DOUBLE PRECISION)) AS "quantidadevendida" 
FROM "alimentosv2"."fat_alimentosv2_FaturamentoBase"
WHERE DATE_TRUNC('YEAR', CAST("data_fatura" AS DATE)) = '2019-01-01'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28